package com.appstek.dc.dbload;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "fnf_lan23_demo3")
public class FnfLanForQC {
	@Id
	@Column(name="ID")
	private String ID;
	@Column(name="APPRCL")
	private String APPRCL;
	@Column(name="STATEPOSTALCODE")
	private String STATEPOSTALCODE;
	@Column(name="COUNTYNAME")
	private String COUNTYNAME;
	@Column(name="APNORPINNUMBER")
	private String APNORPINNUMBER;
	@Column(name="DUPLICATEAPNMULTIADDRESSID")
	private String DUPLICATEAPNMULTIADDRESSID ;
	@Column(name="PROPADDRSRCEFLAG")
	private String PROPADDRSRCEFLAG;
	@Column(name="PROPHOUSENUMBER")
	private String PROPHOUSENUMBER;
	@Column(name="PROPHOUSEALPHA")
	private String PROPHOUSEALPHA; 
	@Column(name="PROPSTREETDIRECTIONLEFT")
	private String PROPSTREETDIRECTIONLEFT; 
	@Column(name="PROPSTREETNAME")
	private String PROPSTREETNAME;
	@Column(name="PROPSTREETSUFFIX")
	private String PROPSTREETSUFFIX;
	@Column(name="PROPSTREETDIRECTIONRIGHT")
	private String PROPSTREETDIRECTIONRIGHT; 
	@Column(name="PROPUNITNUMBER")
	private String PROPUNITNUMBER; 
	@Column(name="PROPFULLSTREETADDRESS")
	private String PROPFULLSTREETADDRESS;
	@Column(name="PROPCITYNAME")
	private String PROPCITYNAME;
	@Column(name="PROPSTATE")
	private String PROPSTATE;
	@Column(name="PROPZIPCODE")
	private String PROPZIPCODE;
	@Column(name="PROPZIP4")
	private String PROPZIP4;
	@Column(name="ASSESSEEOWNERNAME")
	private String ASSESSEEOWNERNAME; 
	@Column(name="SECOND_ASSESSEEOWNERNAME")
	private String SECOND_ASSESSEEOWNERNAME; 
	@Column(name="ASSEVESTINGIDCODE")
	private String ASSEVESTINGIDCODE;
	@Column(name="TAXACCOUNTNUMBER")
	private String TAXACCOUNTNUMBER;
	@Column(name="ASSEMAILCAREOFNAME")
	private String ASSEMAILCAREOFNAME; 
	@Column(name="ASSEMAILHOUSENUMBER")
	private String ASSEMAILHOUSENUMBER;
	@Column(name="ASSEMAILHOUSEALPHA")
	private String ASSEMAILHOUSEALPHA; 
	@Column(name="ASSEMAILSTREETDIRECTIONLEFT")
	private String ASSEMAILSTREETDIRECTIONLEFT; 
	@Column(name="ASSEMAILSTREETNAME")
	private String ASSEMAILSTREETNAME; 
	@Column(name="ASSEMAILSTREETSUFFIX")
	private String ASSEMAILSTREETSUFFIX; 
	@Column(name="ASSEMAILSTREETDIRECTIONRIGHT")
	private String ASSEMAILSTREETDIRECTIONRIGHT; 
	@Column(name="ASSEMAILUNITNUMBER")
	private String ASSEMAILUNITNUMBER; 
	@Column(name="ASSEMAILFULLSTREETADDRESS")
	private String ASSEMAILFULLSTREETADDRESS; 
	@Column(name="ASSEMAILCITYNAME")
	private String ASSEMAILCITYNAME; 
	@Column(name="ASSEMAILSTATE")
	private String ASSEMAILSTATE;
	@Column(name="ASSEMAILZIPCODE")
	private String ASSEMAILZIPCODE;
	@Column(name="ASSEMAILZIP4")
	private String ASSEMAILZIP4;
	@Column(name="STATELANDUSECODE")
	private String STATELANDUSECODE;
	@Column(name="OWNEROCCUPIEDSFRCONDO")
	private String OWNEROCCUPIEDSFRCONDO;
	@Column(name="ASSESSEDLANDVALUE")
	private String ASSESSEDLANDVALUE;
	@Column(name="ASSESSEDIMPROVEMENTVALUE")
	private String ASSESSEDIMPROVEMENTVALUE;
	@Column(name="TOTALASSESSEDVALUE")
	private String TOTALASSESSEDVALUE;
	@Column(name="ASSESSMENTYEAR")
	private String ASSESSMENTYEAR; 
	@Column(name="CALIFHOMEOWNERSEXEMPTION")
	private String CALIFHOMEOWNERSEXEMPTION;
	@Column(name="TAXEXEMPTIONCODE")
	private String TAXEXEMPTIONCODE;
	@Column(name="TAXRATECODEAREA")
	private String TAXRATECODEAREA;
	@Column(name="TAXAMOUNT")
	private String TAXAMOUNT;
	@Column(name="TAXYEAR")
	private String TAXYEAR; 
	@Column(name="TAXDELINQUENTYEAR")
	private String TAXDELINQUENTYEAR;
	@Column(name="RECORDERSDOCUMENTNUMBER")
	private String RECORDERSDOCUMENTNUMBER;
	@Column(name="RECORDERSBOOKNUMBER")
	private String RECORDERSBOOKNUMBER;
	@Column(name="RECORDERSPAGENUMBER")
	private String RECORDERSPAGENUMBER;
	@Column(name="RECORDINGDATE")
	private String RECORDINGDATE;
	@Column(name="DOCUMENTTYPECOUNTYDESCRIPTION")
	private String DOCUMENTTYPECOUNTYDESCRIPTION; 
	@Column(name="SALESPRICE")
	private String SALESPRICE;
	@Column(name="SALESPRICECODE")
	private String SALESPRICECODE;
	@Column(name="PRIORSALEDATE")
	private String PRIORSALEDATE;
	@Column(name="PRIORSALESPRICE")
	private String PRIORSALESPRICE; 
	@Column(name="PRIORSALESCODE")
	private String PRIORSALESCODE;
	@Column(name="LEGALLOTCODE")
	private String LEGALLOTCODE;
	@Column(name="LEGALLOTNUMBER")
	private String LEGALLOTNUMBER; 
	@Column(name="LEGALLANDLOT")
	private String LEGALLANDLOT;
	@Column(name="LEGALBLOCK")
	private String LEGALBLOCK;
	@Column(name="LEGALSECTION")
	private String LEGALSECTION;
	@Column(name="LEGALDISTRICT")
	private String LEGALDISTRICT; 
	@Column(name="LEGALUNIT")
	private String LEGALUNIT;
	@Column(name="LEGALCITYMUNICIPALITYTOWNSHIP")
	private String LEGALCITYMUNICIPALITYTOWNSHIP;
	@Column(name="LEGALSUBDIVISIONNAME")
	private String LEGALSUBDIVISIONNAME;
	@Column(name="LEGALPHASENO")
	private String LEGALPHASENO;
	@Column(name="LEGALTRACTNO")
	private String LEGALTRACTNO;
	@Column(name="LEGALSECTWPRNGMER")
	private String LEGALSECTWPRNGMER;
	@Column(name="LEGALBRIEFDESCRIPTION")
	private String LEGALBRIEFDESCRIPTION;
	@Column(name="LEGALASSESSORSMAPREF")
	private String LEGALASSESSORSMAPREF; 
	@Column(name="COUNTYLANDUSEDESCRIPTION")
	private String COUNTYLANDUSEDESCRIPTION;
	@Column(name="COUNTYLANDUSECODE")
	private String COUNTYLANDUSECODE; 
	@Column(name="STANDARDIZEDLANDUSECODE")
	private String STANDARDIZEDLANDUSECODE; 
	@Column(name="TIMESHARECODE")
	private String TIMESHARECODE;
	@Column(name="ZONING")
	private String ZONING;
	@Column(name="LOTSIZEORAREA")
	private String LOTSIZEORAREA;
	@Column(name="BUILDINGAREA")
	private String BUILDINGAREA;
	@Column(name="YEARBUILT")
	private String YEARBUILT; 
	@Column(name="NOOFBUILDINGS")
	private String NOOFBUILDINGS;
	@Column(name="NOOFSTORIES")
	private String NOOFSTORIES;
	@Column(name="NOOFUNITS")
	private String NOOFUNITS;
	@Column(name="TOTALNOOFROOMS")
	private String TOTALNOOFROOMS;
	@Column(name="NOOFBEDROOMS")
	private String NOOFBEDROOMS; 
	@Column(name="NOOFBATHS")
	private String NOOFBATHS;
	@Column(name="NOOFPARTIALBATHS")
	private String NOOFPARTIALBATHS;
	@Column(name="GARAGETYPEPARKING")
	private String GARAGETYPEPARKING;
	@Column(name="PARKINGNUMBEROFCARS")
	private String PARKINGNUMBEROFCARS;
	@Column(name="POOL")
	private String POOL; 
	@Column(name="MAILCITYSTZIP")
	private String MAILCITYSTZIP;
	@Column(name="FIPSCODE")
	private String FIPSCODE; 
	@Column(name="TAPECUTDATE")                            
	private String TAPECUTDATE; 
	@Column(name="CENSUSTRACT")
	private String CENSUSTRACT;
	@Column(name="RECORDTYPE")
	private String RECORDTYPE;
	@Column(name="MARKETVALUELAND")
	private String MARKETVALUELAND;
	@Column(name="MARKETVALUEIMPROVEMENT")
	private String MARKETVALUEIMPROVEMENT;
	@Column(name="TOTALMARKETVALUE")
	private String TOTALMARKETVALUE;
	@Column(name="MARKETVALUEYEAR")
	private String MARKETVALUEYEAR;
	@Column(name="BUILDINGCLASS")
	private String BUILDINGCLASS;
	@Column(name="STYLE")
	private String STYLE; 
	@Column(name="TYPECONSTRUCTION")
	private String TYPECONSTRUCTION;
	@Column(name="EXTERIORWALLS")
	private String EXTERIORWALLS;
	@Column(name="FOUNDATION")
	private String FOUNDATION;
	@Column(name="ROOFCOVER")
	private String ROOFCOVER; 
	@Column(name="HEATING")
	private String HEATING; 
	@Column(name="AIRCONDITIONING")
	private String AIRCONDITIONING;
	@Column(name="ELEVATOR")
	private String ELEVATOR;
	@Column(name="FIREPLACE")
	private String FIREPLACE;
	@Column(name="BASEMENT")
	private String BASEMENT; 
	@Column(name="EDITIONNUMBER")
	private String EDITIONNUMBER;
	@Column(name="PROPERTYCOUNTRYCODE")
	private String PROPERTYCOUNTRYCODE; 
	@Column(name="BUILDINGAREAINDICATOR")
	private String BUILDINGAREAINDICATOR; 
	@Column(name="PROPADDRMATCHCODE")
	private String PROPADDRMATCHCODE;
	@Column(name="PROPADDRUNITDESIGNATOR")
	private String PROPADDRUNITDESIGNATOR;
	@Column(name="PROPADDRUNITNUMBER")
	private String PROPADDRUNITNUMBER;
	@Column(name="PROPADDRCARRIERROUTE")
	private String PROPADDRCARRIERROUTE; 
	@Column(name="PROPADDRGEOCODEMATCHCODE")
	private String PROPADDRGEOCODEMATCHCODE;
	@Column(name="PROPADDRLATITUDE")
	private String PROPADDRLATITUDE; 
	@Column(name="PROPADDRLONGITUDE")
	private String PROPADDRLONGITUDE;
	@Column(name="PROPADDRCENSUSTRACTBLOCK")
	private String PROPADDRCENSUSTRACTBLOCK;
	@Column(name="MAILADDRMATCHCODE")
	private String MAILADDRMATCHCODE; 
	@Column(name="MAILADDRUNITDESIGNATOR")
	private String MAILADDRUNITDESIGNATOR;
	@Column(name="MAILADDRUNITNUMBER")
	private String MAILADDRUNITNUMBER;
	@Column(name="MAILADDRCARRIERROUTE")
	private String MAILADDRCARRIERROUTE;
	@Column(name="ASSESSEEOWNERNAMEINDICATOR")
	private String ASSESSEEOWNERNAMEINDICATOR;
	@Column(name="SECOND_ASSESSEEOWNER_INDICATOR")
	private String SECOND_ASSESSEEOWNER_INDICATOR;
	@Column(name="MAILCAREOFNAMEINDICATOR")
	private String MAILCAREOFNAMEINDICATOR; 
	@Column(name="ASSESSEEOWNERNAMETYPE")
	private String ASSESSEEOWNERNAMETYPE;
	@Column(name="SECONDASSESSEEOWNERNAMETYPE")
	private String SECONDASSESSEEOWNERNAMETYPE; 
	@Column(name="ALTOLDAPNINDICATOR")
	private String ALTOLDAPNINDICATOR; 
	@Column(name="CERTIFICATIONDATE")
	private String CERTIFICATIONDATE; 
	@Column(name="LOTSIZESQFT")
	private String LOTSIZESQFT;
	@Column(name="BUILDINGQUALITY")
	private String BUILDINGQUALITY;
	@Column(name="FLOORCOVER")
	private String FLOORCOVER; 
	@Column(name="NOOFPLUMBINGFIXTURES")
	private String NOOFPLUMBINGFIXTURES;
	@Column(name="BUILDINGAREA1")
	private String BUILDINGAREA1;
	@Column(name="BUILDINGAREA1INDICATOR")
	private String BUILDINGAREA1INDICATOR;
	@Column(name="BUILDINGAREA2")
	private String BUILDINGAREA2;
	@Column(name="BUILDINGAREA2INDICATOR")
	private String BUILDINGAREA2INDICATOR; 
	@Column(name="BUILDINGAREA3")
	private String BUILDINGAREA3;
	@Column(name="BUILDINGAREA3INDICATOR")
	private String BUILDINGAREA3INDICATOR; 
	@Column(name="BUILDINGAREA4")
	private String BUILDINGAREA4;
	@Column(name="BUILDINGAREA4INDICATOR")
	private String BUILDINGAREA4INDICATOR;
	@Column(name="BUILDINGAREA5")
	private String BUILDINGAREA5;
	@Column(name="BUILDINGAREA5INDICATOR")
	private String BUILDINGAREA5INDICATOR;
	@Column(name="BUILDINGAREA6")
	private String BUILDINGAREA6;
	@Column(name="BUILDINGAREA6INDICATOR")
	private String BUILDINGAREA6INDICATOR ;
	@Column(name="BUILDINGAREA7")
	private String BUILDINGAREA7;
	@Column(name="BUILDINGAREA7INDICATOR")
	private String BUILDINGAREA7INDICATOR;
	@Column(name="EFFECTIVEYEARBUILT")
	private String EFFECTIVEYEARBUILT;
	@Column(name="HEATINGFUELTYPE")
	private String HEATINGFUELTYPE ; 
	@Column(name="AIRCONDITIONINGTYPE")
	private String AIRCONDITIONINGTYPE ;
	@Column(name="LOTSIZEACRES")
	private String LOTSIZEACRES ;
	@Column(name="MORTGAGELENDERNAME")
	private String MORTGAGELENDERNAME ; 
	@Column(name="INTERIORWALLS")
	private String INTERIORWALLS ;
	@Column(name="SCHOOLTAXDISTRICT1")
	private String SCHOOLTAXDISTRICT1;
	@Column(name="SCHOOLTAXDISTRICT1INDICATOR")
	private String SCHOOLTAXDISTRICT1INDICATOR ;
	@Column(name="SCHOOLTAXDISTRICT2")
	private String SCHOOLTAXDISTRICT2 ; 
	@Column(name="SCHOOLTAXDISTRICT2INDICATOR")
	private String SCHOOLTAXDISTRICT2INDICATOR;
	@Column(name="SCHOOLTAXDISTRICT3")
	private String SCHOOLTAXDISTRICT3 ;
	@Column(name="SCHOOLTAXDISTRICT3INDICATOR")
	private String SCHOOLTAXDISTRICT3INDICATOR ;
	@Column(name="SITEINFLUENCE")
	private String SITEINFLUENCE;
	@Column(name="AMENITIES")
	private String AMENITIES ;
	@Column(name="OTHERIMPRBUILDINGINDICATOR1")
	private String OTHERIMPRBUILDINGINDICATOR1 ;
	@Column(name="OTHERIMPRBUILDINGINDICATOR2")
	private String OTHERIMPRBUILDINGINDICATOR2;
	@Column(name="OTHERIMPRBUILDINGINDICATOR3")
	private String OTHERIMPRBUILDINGINDICATOR3 ; 
	@Column(name="OTHERIMPRBUILDINGINDICATOR4")
	private String OTHERIMPRBUILDINGINDICATOR4 ;
	@Column(name="NEIGHBORHOODCODE")
	private String NEIGHBORHOODCODE ;
	@Column(name="CONDOPROJECTBUILDINGNAME")
	private String CONDOPROJECTBUILDINGNAME ;
	@Column(name="OTHERIMPRBUILDINGINDICATOR5")
	private String OTHERIMPRBUILDINGINDICATOR5 ;
	@Column(name="AMENITIES2")
	private String AMENITIES2 ;
	@Column(name="OTHERIMPRBUILDINGAREA1")
	private String OTHERIMPRBUILDINGAREA1;
	@Column(name="OTHERIMPRBUILDINGAREA2")
	private String OTHERIMPRBUILDINGAREA2 ;
	@Column(name="OTHERIMPRBUILDINGAREA3")
	private String OTHERIMPRBUILDINGAREA3 ;
	@Column(name="OTHERIMPRBUILDINGAREA4")
	private String OTHERIMPRBUILDINGAREA4 ; 
	@Column(name="OTHERIMPRBUILDINGAREA5")
	private String OTHERIMPRBUILDINGAREA5;
	@Column(name="OTHERROOMS")
	private String OTHERROOMS;
	@Column(name="EXTRAFEATURES1AREA")
	private String EXTRAFEATURES1AREA ;
	@Column(name="EXTRAFEATURES1INDICATOR")
	private String EXTRAFEATURES1INDICATOR ;
	@Column(name="TOPOGRAPHY")
	private String TOPOGRAPHY ;
	@Column(name="ROOFTYPE")
	private String ROOFTYPE;
	@Column(name="EXTRAFEATURES2AREA")
	private String EXTRAFEATURES2AREA ; 
	@Column(name="EXTRAFEATURES2INDICATOR")
	private String EXTRAFEATURES2INDICATOR ;
	@Column(name="EXTRAFEATURES3AREA")
	private String EXTRAFEATURES3AREA ; 
	@Column(name="EXTRAFEATURES3INDICATOR")
	private String EXTRAFEATURES3INDICATOR ;
	@Column(name="EXTRAFEATURES4AREA")
	private String EXTRAFEATURES4AREA ; 
	@Column(name="EXTRAFEATURES4INDICATOR")
	private String EXTRAFEATURES4INDICATOR ;
	@Column(name="OLDAPN")
	private String OLDAPN ; 
	@Column(name="BUILDINGCONDITION")
	private String BUILDINGCONDITION ; 
	@Column(name="LOTSIZEFRONTAGEFEET")
	private String LOTSIZEFRONTAGEFEET ;
	@Column(name="LOTSIZEDEPTHFEET")
	private String LOTSIZEDEPTHFEET ;
	@Column(name="COMMENTS")
	private String COMMENTS ;
	@Column(name="WATER")
	private String WATER ;
	@Column(name="SEWER")
	private String SEWER ;
	@Column(name="NEWRECORDTYPE")
	private String NEWRECORDTYPE ;
	public String getAPPRCL() {
	return APPRCL;
	}
	public void setAPPRCL(String aPPRCL) {
	APPRCL = aPPRCL;
	}
	public String getSTATEPOSTALCODE() {
	return STATEPOSTALCODE;
	}
	public void setSTATEPOSTALCODE(String sTATEPOSTALCODE) {
	STATEPOSTALCODE = sTATEPOSTALCODE;
	}
	public String getCOUNTYNAME() {
	return COUNTYNAME;
	}
	public void setCOUNTYNAME(String cOUNTYNAME) {
	COUNTYNAME = cOUNTYNAME;
	}
	public String getAPNORPINNUMBER() {
	return APNORPINNUMBER;
	}
	public void setAPNORPINNUMBER(String aPNORPINNUMBER) {
	APNORPINNUMBER = aPNORPINNUMBER;
	}
	public String getDUPLICATEAPNMULTIADDRESSID() {
	return DUPLICATEAPNMULTIADDRESSID;
	}
	public void setDUPLICATEAPNMULTIADDRESSID(String dUPLICATEAPNMULTIADDRESSID) {
	DUPLICATEAPNMULTIADDRESSID = dUPLICATEAPNMULTIADDRESSID;
	}
	public String getPROPADDRSRCEFLAG() {
	return PROPADDRSRCEFLAG;
	}
	public void setPROPADDRSRCEFLAG(String pROPADDRSRCEFLAG) {
	PROPADDRSRCEFLAG = pROPADDRSRCEFLAG;
	}
	public String getPROPHOUSENUMBER() {
	return PROPHOUSENUMBER;
	}
	public void setPROPHOUSENUMBER(String pROPHOUSENUMBER) {
	PROPHOUSENUMBER = pROPHOUSENUMBER;
	}
	public String getPROPHOUSEALPHA() {
	return PROPHOUSEALPHA;
	}
	public void setPROPHOUSEALPHA(String pROPHOUSEALPHA) {
	PROPHOUSEALPHA = pROPHOUSEALPHA;
	}
	public String getPROPSTREETDIRECTIONLEFT() {
	return PROPSTREETDIRECTIONLEFT;
	}
	public void setPROPSTREETDIRECTIONLEFT(String pROPSTREETDIRECTIONLEFT) {
	PROPSTREETDIRECTIONLEFT = pROPSTREETDIRECTIONLEFT;
	}
	public String getPROPSTREETNAME() {
	return PROPSTREETNAME;
	}
	public void setPROPSTREETNAME(String pROPSTREETNAME) {
	PROPSTREETNAME = pROPSTREETNAME;
	}
	public String getPROPSTREETSUFFIX() {
	return PROPSTREETSUFFIX;
	}
	public void setPROPSTREETSUFFIX(String pROPSTREETSUFFIX) {
	PROPSTREETSUFFIX = pROPSTREETSUFFIX;
	}
	public String getPROPSTREETDIRECTIONRIGHT() {
	return PROPSTREETDIRECTIONRIGHT;
	}
	public void setPROPSTREETDIRECTIONRIGHT(String pROPSTREETDIRECTIONRIGHT) {
	PROPSTREETDIRECTIONRIGHT = pROPSTREETDIRECTIONRIGHT;
	}
	public String getPROPUNITNUMBER() {
	return PROPUNITNUMBER;
	}
	public void setPROPUNITNUMBER(String pROPUNITNUMBER) {
	PROPUNITNUMBER = pROPUNITNUMBER;
	}
	public String getPROPFULLSTREETADDRESS() {
	return PROPFULLSTREETADDRESS;
	}
	public void setPROPFULLSTREETADDRESS(String pROPFULLSTREETADDRESS) {
	PROPFULLSTREETADDRESS = pROPFULLSTREETADDRESS;
	}
	public String getPROPCITYNAME() {
	return PROPCITYNAME;
	}
	public void setPROPCITYNAME(String pROPCITYNAME) {
	PROPCITYNAME = pROPCITYNAME;
	}
	public String getPROPSTATE() {
	return PROPSTATE;
	}
	public void setPROPSTATE(String pROPSTATE) {
	PROPSTATE = pROPSTATE;
	}
	public String getPROPZIPCODE() {
	return PROPZIPCODE;
	}
	public void setPROPZIPCODE(String pROPZIPCODE) {
	PROPZIPCODE = pROPZIPCODE;
	}
	public String getPROPZIP4() {
	return PROPZIP4;
	}
	public void setPROPZIP4(String pROPZIP4) {
	PROPZIP4 = pROPZIP4;
	}
	public String getASSESSEEOWNERNAME() {
	return ASSESSEEOWNERNAME;
	}
	public void setASSESSEEOWNERNAME(String aSSESSEEOWNERNAME) {
	ASSESSEEOWNERNAME = aSSESSEEOWNERNAME;
	}
	public String getSECOND_ASSESSEEOWNERNAME() {
	return SECOND_ASSESSEEOWNERNAME;
	}
	public void setSECOND_ASSESSEEOWNERNAME(String sECOND_ASSESSEEOWNERNAME) {
	SECOND_ASSESSEEOWNERNAME = sECOND_ASSESSEEOWNERNAME;
	}
	public String getASSEVESTINGIDCODE() {
	return ASSEVESTINGIDCODE;
	}
	public void setASSEVESTINGIDCODE(String aSSEVESTINGIDCODE) {
	ASSEVESTINGIDCODE = aSSEVESTINGIDCODE;
	}
	public String getTAXACCOUNTNUMBER() {
	return TAXACCOUNTNUMBER;
	}
	public void setTAXACCOUNTNUMBER(String tAXACCOUNTNUMBER) {
	TAXACCOUNTNUMBER = tAXACCOUNTNUMBER;
	}
	public String getASSEMAILCAREOFNAME() {
	return ASSEMAILCAREOFNAME;
	}
	public void setASSEMAILCAREOFNAME(String aSSEMAILCAREOFNAME) {
	ASSEMAILCAREOFNAME = aSSEMAILCAREOFNAME;
	}
	public String getASSEMAILHOUSENUMBER() {
	return ASSEMAILHOUSENUMBER;
	}
	public void setASSEMAILHOUSENUMBER(String aSSEMAILHOUSENUMBER) {
	ASSEMAILHOUSENUMBER = aSSEMAILHOUSENUMBER;
	}
	public String getASSEMAILHOUSEALPHA() {
	return ASSEMAILHOUSEALPHA;
	}
	public void setASSEMAILHOUSEALPHA(String aSSEMAILHOUSEALPHA) {
	ASSEMAILHOUSEALPHA = aSSEMAILHOUSEALPHA;
	}
	public String getASSEMAILSTREETDIRECTIONLEFT() {
	return ASSEMAILSTREETDIRECTIONLEFT;
	}
	public void setASSEMAILSTREETDIRECTIONLEFT(String aSSEMAILSTREETDIRECTIONLEFT) {
	ASSEMAILSTREETDIRECTIONLEFT = aSSEMAILSTREETDIRECTIONLEFT;
	}
	public String getASSEMAILSTREETNAME() {
	return ASSEMAILSTREETNAME;
	}
	public void setASSEMAILSTREETNAME(String aSSEMAILSTREETNAME) {
	ASSEMAILSTREETNAME = aSSEMAILSTREETNAME;
	}
	public String getASSEMAILSTREETSUFFIX() {
	return ASSEMAILSTREETSUFFIX;
	}
	public void setASSEMAILSTREETSUFFIX(String aSSEMAILSTREETSUFFIX) {
	ASSEMAILSTREETSUFFIX = aSSEMAILSTREETSUFFIX;
	}
	public String getASSEMAILSTREETDIRECTIONRIGHT() {
	return ASSEMAILSTREETDIRECTIONRIGHT;
	}
	public void setASSEMAILSTREETDIRECTIONRIGHT(String aSSEMAILSTREETDIRECTIONRIGHT) {
	ASSEMAILSTREETDIRECTIONRIGHT = aSSEMAILSTREETDIRECTIONRIGHT;
	}
	public String getASSEMAILUNITNUMBER() {
	return ASSEMAILUNITNUMBER;
	}
	public void setASSEMAILUNITNUMBER(String aSSEMAILUNITNUMBER) {
	ASSEMAILUNITNUMBER = aSSEMAILUNITNUMBER;
	}
	public String getASSEMAILFULLSTREETADDRESS() {
	return ASSEMAILFULLSTREETADDRESS;
	}
	public void setASSEMAILFULLSTREETADDRESS(String aSSEMAILFULLSTREETADDRESS) {
	ASSEMAILFULLSTREETADDRESS = aSSEMAILFULLSTREETADDRESS;
	}
	public String getASSEMAILCITYNAME() {
	return ASSEMAILCITYNAME;
	}
	public void setASSEMAILCITYNAME(String aSSEMAILCITYNAME) {
	ASSEMAILCITYNAME = aSSEMAILCITYNAME;
	}
	public String getASSEMAILSTATE() {
	return ASSEMAILSTATE;
	}
	public void setASSEMAILSTATE(String aSSEMAILSTATE) {
	ASSEMAILSTATE = aSSEMAILSTATE;
	}
	public String getASSEMAILZIPCODE() {
	return ASSEMAILZIPCODE;
	}
	public void setASSEMAILZIPCODE(String aSSEMAILZIPCODE) {
	ASSEMAILZIPCODE = aSSEMAILZIPCODE;
	}
	public String getASSEMAILZIP4() {
	return ASSEMAILZIP4;
	}
	public void setASSEMAILZIP4(String aSSEMAILZIP4) {
	ASSEMAILZIP4 = aSSEMAILZIP4;
	}
	public String getSTATELANDUSECODE() {
	return STATELANDUSECODE;
	}
	public void setSTATELANDUSECODE(String sTATELANDUSECODE) {
	STATELANDUSECODE = sTATELANDUSECODE;
	}
	public String getOWNEROCCUPIEDSFRCONDO() {
	return OWNEROCCUPIEDSFRCONDO;
	}
	public void setOWNEROCCUPIEDSFRCONDO(String oWNEROCCUPIEDSFRCONDO) {
	OWNEROCCUPIEDSFRCONDO = oWNEROCCUPIEDSFRCONDO;
	}
	public String getASSESSEDLANDVALUE() {
	return ASSESSEDLANDVALUE;
	}
	public void setASSESSEDLANDVALUE(String aSSESSEDLANDVALUE) {
	ASSESSEDLANDVALUE = aSSESSEDLANDVALUE;
	}
	public String getASSESSEDIMPROVEMENTVALUE() {
	return ASSESSEDIMPROVEMENTVALUE;
	}
	public void setASSESSEDIMPROVEMENTVALUE(String aSSESSEDIMPROVEMENTVALUE) {
	ASSESSEDIMPROVEMENTVALUE = aSSESSEDIMPROVEMENTVALUE;
	}
	public String getTOTALASSESSEDVALUE() {
	return TOTALASSESSEDVALUE;
	}
	public void setTOTALASSESSEDVALUE(String tOTALASSESSEDVALUE) {
	TOTALASSESSEDVALUE = tOTALASSESSEDVALUE;
	}
	public String getASSESSMENTYEAR() {
	return ASSESSMENTYEAR;
	}
	public void setASSESSMENTYEAR(String aSSESSMENTYEAR) {
	ASSESSMENTYEAR = aSSESSMENTYEAR;
	}
	public String getCALIFHOMEOWNERSEXEMPTION() {
	return CALIFHOMEOWNERSEXEMPTION;
	}
	public void setCALIFHOMEOWNERSEXEMPTION(String cALIFHOMEOWNERSEXEMPTION) {
	CALIFHOMEOWNERSEXEMPTION = cALIFHOMEOWNERSEXEMPTION;
	}
	public String getTAXEXEMPTIONCODE() {
	return TAXEXEMPTIONCODE;
	}
	public void setTAXEXEMPTIONCODE(String tAXEXEMPTIONCODE) {
	TAXEXEMPTIONCODE = tAXEXEMPTIONCODE;
	}
	public String getTAXRATECODEAREA() {
	return TAXRATECODEAREA;
	}
	public void setTAXRATECODEAREA(String tAXRATECODEAREA) {
	TAXRATECODEAREA = tAXRATECODEAREA;
	}
	public String getTAXAMOUNT() {
	return TAXAMOUNT;
	}
	public void setTAXAMOUNT(String tAXAMOUNT) {
	TAXAMOUNT = tAXAMOUNT;
	}
	public String getTAXYEAR() {
	return TAXYEAR;
	}
	public void setTAXYEAR(String tAXYEAR) {
	TAXYEAR = tAXYEAR;
	}
	public String getTAXDELINQUENTYEAR() {
	return TAXDELINQUENTYEAR;
	}
	public void setTAXDELINQUENTYEAR(String tAXDELINQUENTYEAR) {
	TAXDELINQUENTYEAR = tAXDELINQUENTYEAR;
	}
	public String getRECORDERSDOCUMENTNUMBER() {
	return RECORDERSDOCUMENTNUMBER;
	}
	public void setRECORDERSDOCUMENTNUMBER(String rECORDERSDOCUMENTNUMBER) {
	RECORDERSDOCUMENTNUMBER = rECORDERSDOCUMENTNUMBER;
	}
	public String getRECORDERSBOOKNUMBER() {
	return RECORDERSBOOKNUMBER;
	}
	public void setRECORDERSBOOKNUMBER(String rECORDERSBOOKNUMBER) {
	RECORDERSBOOKNUMBER = rECORDERSBOOKNUMBER;
	}
	public String getRECORDERSPAGENUMBER() {
	return RECORDERSPAGENUMBER;
	}
	public void setRECORDERSPAGENUMBER(String rECORDERSPAGENUMBER) {
	RECORDERSPAGENUMBER = rECORDERSPAGENUMBER;
	}
	public String getRECORDINGDATE() {
	return RECORDINGDATE;
	}
	public void setRECORDINGDATE(String rECORDINGDATE) {
	RECORDINGDATE = rECORDINGDATE;
	}
	public String getDOCUMENTTYPECOUNTYDESCRIPTION() {
	return DOCUMENTTYPECOUNTYDESCRIPTION;
	}
	public void setDOCUMENTTYPECOUNTYDESCRIPTION(String dOCUMENTTYPECOUNTYDESCRIPTION) {
	DOCUMENTTYPECOUNTYDESCRIPTION = dOCUMENTTYPECOUNTYDESCRIPTION;
	}
	public String getSALESPRICE() {
	return SALESPRICE;
	}
	public void setSALESPRICE(String sALESPRICE) {
	SALESPRICE = sALESPRICE;
	}
	public String getSALESPRICECODE() {
	return SALESPRICECODE;
	}
	public void setSALESPRICECODE(String sALESPRICECODE) {
	SALESPRICECODE = sALESPRICECODE;
	}
	public String getPRIORSALEDATE() {
	return PRIORSALEDATE;
	}
	public void setPRIORSALEDATE(String pRIORSALEDATE) {
	PRIORSALEDATE = pRIORSALEDATE;
	}
	public String getPRIORSALESPRICE() {
	return PRIORSALESPRICE;
	}
	public void setPRIORSALESPRICE(String pRIORSALESPRICE) {
	PRIORSALESPRICE = pRIORSALESPRICE;
	}
	public String getPRIORSALESCODE() {
	return PRIORSALESCODE;
	}
	public void setPRIORSALESCODE(String pRIORSALESCODE) {
	PRIORSALESCODE = pRIORSALESCODE;
	}
	public String getLEGALLOTCODE() {
	return LEGALLOTCODE;
	}
	public void setLEGALLOTCODE(String lEGALLOTCODE) {
	LEGALLOTCODE = lEGALLOTCODE;
	}
	public String getLEGALLOTNUMBER() {
	return LEGALLOTNUMBER;
	}
	public void setLEGALLOTNUMBER(String lEGALLOTNUMBER) {
	LEGALLOTNUMBER = lEGALLOTNUMBER;
	}
	public String getLEGALLANDLOT() {
	return LEGALLANDLOT;
	}
	public void setLEGALLANDLOT(String lEGALLANDLOT) {
	LEGALLANDLOT = lEGALLANDLOT;
	}
	public String getLEGALBLOCK() {
	return LEGALBLOCK;
	}
	public void setLEGALBLOCK(String lEGALBLOCK) {
	LEGALBLOCK = lEGALBLOCK;
	}
	public String getLEGALSECTION() {
	return LEGALSECTION;
	}
	public void setLEGALSECTION(String lEGALSECTION) {
	LEGALSECTION = lEGALSECTION;
	}
	public String getLEGALDISTRICT() {
	return LEGALDISTRICT;
	}
	public void setLEGALDISTRICT(String lEGALDISTRICT) {
	LEGALDISTRICT = lEGALDISTRICT;
	}
	public String getLEGALUNIT() {
	return LEGALUNIT;
	}
	public void setLEGALUNIT(String lEGALUNIT) {
	LEGALUNIT = lEGALUNIT;
	}
	public String getLEGALCITYMUNICIPALITYTOWNSHIP() {
	return LEGALCITYMUNICIPALITYTOWNSHIP;
	}
	public void setLEGALCITYMUNICIPALITYTOWNSHIP(String lEGALCITYMUNICIPALITYTOWNSHIP) {
	LEGALCITYMUNICIPALITYTOWNSHIP = lEGALCITYMUNICIPALITYTOWNSHIP;
	}
	public String getLEGALSUBDIVISIONNAME() {
	return LEGALSUBDIVISIONNAME;
	}
	public void setLEGALSUBDIVISIONNAME(String lEGALSUBDIVISIONNAME) {
	LEGALSUBDIVISIONNAME = lEGALSUBDIVISIONNAME;
	}
	public String getLEGALPHASENO() {
	return LEGALPHASENO;
	}
	public void setLEGALPHASENO(String lEGALPHASENO) {
	LEGALPHASENO = lEGALPHASENO;
	}
	public String getLEGALTRACTNO() {
	return LEGALTRACTNO;
	}
	public void setLEGALTRACTNO(String lEGALTRACTNO) {
	LEGALTRACTNO = lEGALTRACTNO;
	}
	public String getLEGALSECTWPRNGMER() {
	return LEGALSECTWPRNGMER;
	}
	public void setLEGALSECTWPRNGMER(String lEGALSECTWPRNGMER) {
	LEGALSECTWPRNGMER = lEGALSECTWPRNGMER;
	}
	public String getLEGALBRIEFDESCRIPTION() {
	return LEGALBRIEFDESCRIPTION;
	}
	public void setLEGALBRIEFDESCRIPTION(String lEGALBRIEFDESCRIPTION) {
	LEGALBRIEFDESCRIPTION = lEGALBRIEFDESCRIPTION;
	}
	public String getLEGALASSESSORSMAPREF() {
	return LEGALASSESSORSMAPREF;
	}
	public void setLEGALASSESSORSMAPREF(String lEGALASSESSORSMAPREF) {
	LEGALASSESSORSMAPREF = lEGALASSESSORSMAPREF;
	}
	public String getCOUNTYLANDUSEDESCRIPTION() {
	return COUNTYLANDUSEDESCRIPTION;
	}
	public void setCOUNTYLANDUSEDESCRIPTION(String cOUNTYLANDUSEDESCRIPTION) {
	COUNTYLANDUSEDESCRIPTION = cOUNTYLANDUSEDESCRIPTION;
	}
	public String getCOUNTYLANDUSECODE() {
	return COUNTYLANDUSECODE;
	}
	public void setCOUNTYLANDUSECODE(String cOUNTYLANDUSECODE) {
	COUNTYLANDUSECODE = cOUNTYLANDUSECODE;
	}
	public String getSTANDARDIZEDLANDUSECODE() {
	return STANDARDIZEDLANDUSECODE;
	}
	public void setSTANDARDIZEDLANDUSECODE(String sTANDARDIZEDLANDUSECODE) {
	STANDARDIZEDLANDUSECODE = sTANDARDIZEDLANDUSECODE;
	}
	public String getTIMESHARECODE() {
	return TIMESHARECODE;
	}
	public void setTIMESHARECODE(String tIMESHARECODE) {
	TIMESHARECODE = tIMESHARECODE;
	}
	public String getZONING() {
	return ZONING;
	}
	public void setZONING(String zONING) {
	ZONING = zONING;
	}
	public String getLOTSIZEORAREA() {
	return LOTSIZEORAREA;
	}
	public void setLOTSIZEORAREA(String lOTSIZEORAREA) {
	LOTSIZEORAREA = lOTSIZEORAREA;
	}
	public String getBUILDINGAREA() {
	return BUILDINGAREA;
	}
	public void setBUILDINGAREA(String bUILDINGAREA) {
	BUILDINGAREA = bUILDINGAREA;
	}
	public String getYEARBUILT() {
	return YEARBUILT;
	}
	public void setYEARBUILT(String yEARBUILT) {
	YEARBUILT = yEARBUILT;
	}
	public String getNOOFBUILDINGS() {
	return NOOFBUILDINGS;
	}
	public void setNOOFBUILDINGS(String nOOFBUILDINGS) {
	NOOFBUILDINGS = nOOFBUILDINGS;
	}
	public String getNOOFSTORIES() {
	return NOOFSTORIES;
	}
	public void setNOOFSTORIES(String nOOFSTORIES) {
	NOOFSTORIES = nOOFSTORIES;
	}
	public String getNOOFUNITS() {
	return NOOFUNITS;
	}
	public void setNOOFUNITS(String nOOFUNITS) {
	NOOFUNITS = nOOFUNITS;
	}
	public String getTOTALNOOFROOMS() {
	return TOTALNOOFROOMS;
	}
	public void setTOTALNOOFROOMS(String tOTALNOOFROOMS) {
	TOTALNOOFROOMS = tOTALNOOFROOMS;
	}
	public String getNOOFBEDROOMS() {
	return NOOFBEDROOMS;
	}
	public void setNOOFBEDROOMS(String nOOFBEDROOMS) {
	NOOFBEDROOMS = nOOFBEDROOMS;
	}
	public String getNOOFBATHS() {
	return NOOFBATHS;
	}
	public void setNOOFBATHS(String nOOFBATHS) {
	NOOFBATHS = nOOFBATHS;
	}
	public String getNOOFPARTIALBATHS() {
	return NOOFPARTIALBATHS;
	}
	public void setNOOFPARTIALBATHS(String nOOFPARTIALBATHS) {
	NOOFPARTIALBATHS = nOOFPARTIALBATHS;
	}
	public String getGARAGETYPEPARKING() {
	return GARAGETYPEPARKING;
	}
	public void setGARAGETYPEPARKING(String gARAGETYPEPARKING) {
	GARAGETYPEPARKING = gARAGETYPEPARKING;
	}
	public String getPARKINGNUMBEROFCARS() {
	return PARKINGNUMBEROFCARS;
	}
	public void setPARKINGNUMBEROFCARS(String pARKINGNUMBEROFCARS) {
	PARKINGNUMBEROFCARS = pARKINGNUMBEROFCARS;
	}
	public String getPOOL() {
	return POOL;
	}
	public void setPOOL(String pOOL) {
	POOL = pOOL;
	}
	public String getMAILCITYSTZIP() {
	return MAILCITYSTZIP;
	}
	public void setMAILCITYSTZIP(String mAILCITYSTZIP) {
	MAILCITYSTZIP = mAILCITYSTZIP;
	}
	public String getFIPSCODE() {
	return FIPSCODE;
	}
	public void setFIPSCODE(String fIPSCODE) {
	FIPSCODE = fIPSCODE;
	}
	public String getTAPECUTDATE() {
	return TAPECUTDATE;
	}
	public void setTAPECUTDATE(String tAPECUTDATE) {
	TAPECUTDATE = tAPECUTDATE;
	}
	public String getCENSUSTRACT() {
	return CENSUSTRACT;
	}
	public void setCENSUSTRACT(String cENSUSTRACT) {
	CENSUSTRACT = cENSUSTRACT;
	}
	public String getRECORDTYPE() {
	return RECORDTYPE;
	}
	public void setRECORDTYPE(String rECORDTYPE) {
	RECORDTYPE = rECORDTYPE;
	}
	public String getMARKETVALUELAND() {
	return MARKETVALUELAND;
	}
	public void setMARKETVALUELAND(String mARKETVALUELAND) {
	MARKETVALUELAND = mARKETVALUELAND;
	}
	public String getMARKETVALUEIMPROVEMENT() {
	return MARKETVALUEIMPROVEMENT;
	}
	public void setMARKETVALUEIMPROVEMENT(String mARKETVALUEIMPROVEMENT) {
	MARKETVALUEIMPROVEMENT = mARKETVALUEIMPROVEMENT;
	}
	public String getTOTALMARKETVALUE() {
	return TOTALMARKETVALUE;
	}
	public void setTOTALMARKETVALUE(String tOTALMARKETVALUE) {
	TOTALMARKETVALUE = tOTALMARKETVALUE;
	}
	public String getMARKETVALUEYEAR() {
	return MARKETVALUEYEAR;
	}
	public void setMARKETVALUEYEAR(String mARKETVALUEYEAR) {
	MARKETVALUEYEAR = mARKETVALUEYEAR;
	}
	public String getBUILDINGCLASS() {
	return BUILDINGCLASS;
	}
	public void setBUILDINGCLASS(String bUILDINGCLASS) {
	BUILDINGCLASS = bUILDINGCLASS;
	}
	public String getSTYLE() {
	return STYLE;
	}
	public void setSTYLE(String sTYLE) {
	STYLE = sTYLE;
	}
	public String getTYPECONSTRUCTION() {
	return TYPECONSTRUCTION;
	}
	public void setTYPECONSTRUCTION(String tYPECONSTRUCTION) {
	TYPECONSTRUCTION = tYPECONSTRUCTION;
	}
	public String getEXTERIORWALLS() {
	return EXTERIORWALLS;
	}
	public void setEXTERIORWALLS(String eXTERIORWALLS) {
	EXTERIORWALLS = eXTERIORWALLS;
	}
	public String getFOUNDATION() {
	return FOUNDATION;
	}
	public void setFOUNDATION(String fOUNDATION) {
	FOUNDATION = fOUNDATION;
	}
	public String getROOFCOVER() {
	return ROOFCOVER;
	}
	public void setROOFCOVER(String rOOFCOVER) {
	ROOFCOVER = rOOFCOVER;
	}
	public String getHEATING() {
	return HEATING;
	}
	public void setHEATING(String hEATING) {
	HEATING = hEATING;
	}
	public String getAIRCONDITIONING() {
	return AIRCONDITIONING;
	}
	public void setAIRCONDITIONING(String aIRCONDITIONING) {
	AIRCONDITIONING = aIRCONDITIONING;
	}
	public String getELEVATOR() {
	return ELEVATOR;
	}
	public void setELEVATOR(String eLEVATOR) {
	ELEVATOR = eLEVATOR;
	}
	public String getFIREPLACE() {
	return FIREPLACE;
	}
	public void setFIREPLACE(String fIREPLACE) {
	FIREPLACE = fIREPLACE;
	}
	public String getBASEMENT() {
	return BASEMENT;
	}
	public void setBASEMENT(String bASEMENT) {
	BASEMENT = bASEMENT;
	}
	public String getEDITIONNUMBER() {
	return EDITIONNUMBER;
	}
	public void setEDITIONNUMBER(String eDITIONNUMBER) {
	EDITIONNUMBER = eDITIONNUMBER;
	}
	public String getPROPERTYCOUNTRYCODE() {
	return PROPERTYCOUNTRYCODE;
	}
	public void setPROPERTYCOUNTRYCODE(String pROPERTYCOUNTRYCODE) {
	PROPERTYCOUNTRYCODE = pROPERTYCOUNTRYCODE;
	}
	public String getBUILDINGAREAINDICATOR() {
	return BUILDINGAREAINDICATOR;
	}
	public void setBUILDINGAREAINDICATOR(String bUILDINGAREAINDICATOR) {
	BUILDINGAREAINDICATOR = bUILDINGAREAINDICATOR;
	}
	public String getPROPADDRMATCHCODE() {
	return PROPADDRMATCHCODE;
	}
	public void setPROPADDRMATCHCODE(String pROPADDRMATCHCODE) {
	PROPADDRMATCHCODE = pROPADDRMATCHCODE;
	}
	public String getPROPADDRUNITDESIGNATOR() {
	return PROPADDRUNITDESIGNATOR;
	}
	public void setPROPADDRUNITDESIGNATOR(String pROPADDRUNITDESIGNATOR) {
	PROPADDRUNITDESIGNATOR = pROPADDRUNITDESIGNATOR;
	}
	public String getPROPADDRUNITNUMBER() {
	return PROPADDRUNITNUMBER;
	}
	public void setPROPADDRUNITNUMBER(String pROPADDRUNITNUMBER) {
	PROPADDRUNITNUMBER = pROPADDRUNITNUMBER;
	}
	public String getPROPADDRCARRIERROUTE() {
	return PROPADDRCARRIERROUTE;
	}
	public void setPROPADDRCARRIERROUTE(String pROPADDRCARRIERROUTE) {
	PROPADDRCARRIERROUTE = pROPADDRCARRIERROUTE;
	}
	public String getPROPADDRGEOCODEMATCHCODE() {
	return PROPADDRGEOCODEMATCHCODE;
	}
	public void setPROPADDRGEOCODEMATCHCODE(String pROPADDRGEOCODEMATCHCODE) {
	PROPADDRGEOCODEMATCHCODE = pROPADDRGEOCODEMATCHCODE;
	}
	public String getPROPADDRLATITUDE() {
	return PROPADDRLATITUDE;
	}
	public void setPROPADDRLATITUDE(String pROPADDRLATITUDE) {
	PROPADDRLATITUDE = pROPADDRLATITUDE;
	}
	public String getPROPADDRLONGITUDE() {
	return PROPADDRLONGITUDE;
	}
	public void setPROPADDRLONGITUDE(String pROPADDRLONGITUDE) {
	PROPADDRLONGITUDE = pROPADDRLONGITUDE;
	}
	public String getPROPADDRCENSUSTRACTBLOCK() {
	return PROPADDRCENSUSTRACTBLOCK;
	}
	public void setPROPADDRCENSUSTRACTBLOCK(String pROPADDRCENSUSTRACTBLOCK) {
	PROPADDRCENSUSTRACTBLOCK = pROPADDRCENSUSTRACTBLOCK;
	}
	public String getMAILADDRMATCHCODE() {
	return MAILADDRMATCHCODE;
	}
	public void setMAILADDRMATCHCODE(String mAILADDRMATCHCODE) {
	MAILADDRMATCHCODE = mAILADDRMATCHCODE;
	}
	public String getMAILADDRUNITDESIGNATOR() {
	return MAILADDRUNITDESIGNATOR;
	}
	public void setMAILADDRUNITDESIGNATOR(String mAILADDRUNITDESIGNATOR) {
	MAILADDRUNITDESIGNATOR = mAILADDRUNITDESIGNATOR;
	}
	public String getMAILADDRUNITNUMBER() {
	return MAILADDRUNITNUMBER;
	}
	public void setMAILADDRUNITNUMBER(String mAILADDRUNITNUMBER) {
	MAILADDRUNITNUMBER = mAILADDRUNITNUMBER;
	}
	public String getMAILADDRCARRIERROUTE() {
	return MAILADDRCARRIERROUTE;
	}
	public void setMAILADDRCARRIERROUTE(String mAILADDRCARRIERROUTE) {
	MAILADDRCARRIERROUTE = mAILADDRCARRIERROUTE;
	}
	public String getASSESSEEOWNERNAMEINDICATOR() {
	return ASSESSEEOWNERNAMEINDICATOR;
	}
	public void setASSESSEEOWNERNAMEINDICATOR(String aSSESSEEOWNERNAMEINDICATOR) {
	ASSESSEEOWNERNAMEINDICATOR = aSSESSEEOWNERNAMEINDICATOR;
	}
	public String getSECOND_ASSESSEEOWNER_INDICATOR() {
	return SECOND_ASSESSEEOWNER_INDICATOR;
	}
	public void setSECOND_ASSESSEEOWNER_INDICATOR(String sECOND_ASSESSEEOWNER_INDICATOR) {
	SECOND_ASSESSEEOWNER_INDICATOR = sECOND_ASSESSEEOWNER_INDICATOR;
	}
	public String getMAILCAREOFNAMEINDICATOR() {
	return MAILCAREOFNAMEINDICATOR;
	}
	public void setMAILCAREOFNAMEINDICATOR(String mAILCAREOFNAMEINDICATOR) {
	MAILCAREOFNAMEINDICATOR = mAILCAREOFNAMEINDICATOR;
	}
	public String getASSESSEEOWNERNAMETYPE() {
	return ASSESSEEOWNERNAMETYPE;
	}
	public void setASSESSEEOWNERNAMETYPE(String aSSESSEEOWNERNAMETYPE) {
	ASSESSEEOWNERNAMETYPE = aSSESSEEOWNERNAMETYPE;
	}
	public String getSECONDASSESSEEOWNERNAMETYPE() {
	return SECONDASSESSEEOWNERNAMETYPE;
	}
	public void setSECONDASSESSEEOWNERNAMETYPE(String sECONDASSESSEEOWNERNAMETYPE) {
	SECONDASSESSEEOWNERNAMETYPE = sECONDASSESSEEOWNERNAMETYPE;
	}
	public String getALTOLDAPNINDICATOR() {
	return ALTOLDAPNINDICATOR;
	}
	public void setALTOLDAPNINDICATOR(String aLTOLDAPNINDICATOR) {
	ALTOLDAPNINDICATOR = aLTOLDAPNINDICATOR;
	}
	public String getCERTIFICATIONDATE() {
	return CERTIFICATIONDATE;
	}
	public void setCERTIFICATIONDATE(String cERTIFICATIONDATE) {
	CERTIFICATIONDATE = cERTIFICATIONDATE;
	}
	public String getLOTSIZESQFT() {
	return LOTSIZESQFT;
	}
	public void setLOTSIZESQFT(String lOTSIZESQFT) {
	LOTSIZESQFT = lOTSIZESQFT;
	}
	public String getBUILDINGQUALITY() {
	return BUILDINGQUALITY;
	}
	public void setBUILDINGQUALITY(String bUILDINGQUALITY) {
	BUILDINGQUALITY = bUILDINGQUALITY;
	}
	public String getFLOORCOVER() {
	return FLOORCOVER;
	}
	public void setFLOORCOVER(String fLOORCOVER) {
	FLOORCOVER = fLOORCOVER;
	}
	public String getNOOFPLUMBINGFIXTURES() {
	return NOOFPLUMBINGFIXTURES;
	}
	public void setNOOFPLUMBINGFIXTURES(String nOOFPLUMBINGFIXTURES) {
	NOOFPLUMBINGFIXTURES = nOOFPLUMBINGFIXTURES;
	}
	public String getBUILDINGAREA1() {
	return BUILDINGAREA1;
	}
	public void setBUILDINGAREA1(String bUILDINGAREA1) {
	BUILDINGAREA1 = bUILDINGAREA1;
	}
	public String getBUILDINGAREA1INDICATOR() {
	return BUILDINGAREA1INDICATOR;
	}
	public void setBUILDINGAREA1INDICATOR(String bUILDINGAREA1INDICATOR) {
	BUILDINGAREA1INDICATOR = bUILDINGAREA1INDICATOR;
	}
	public String getBUILDINGAREA2() {
	return BUILDINGAREA2;
	}
	public void setBUILDINGAREA2(String bUILDINGAREA2) {
	BUILDINGAREA2 = bUILDINGAREA2;
	}
	public String getBUILDINGAREA2INDICATOR() {
	return BUILDINGAREA2INDICATOR;
	}
	public void setBUILDINGAREA2INDICATOR(String bUILDINGAREA2INDICATOR) {
	BUILDINGAREA2INDICATOR = bUILDINGAREA2INDICATOR;
	}
	public String getBUILDINGAREA3() {
	return BUILDINGAREA3;
	}
	public void setBUILDINGAREA3(String bUILDINGAREA3) {
	BUILDINGAREA3 = bUILDINGAREA3;
	}
	public String getBUILDINGAREA3INDICATOR() {
	return BUILDINGAREA3INDICATOR;
	}
	public void setBUILDINGAREA3INDICATOR(String bUILDINGAREA3INDICATOR) {
	BUILDINGAREA3INDICATOR = bUILDINGAREA3INDICATOR;
	}
	public String getBUILDINGAREA4() {
	return BUILDINGAREA4;
	}
	public void setBUILDINGAREA4(String bUILDINGAREA4) {
	BUILDINGAREA4 = bUILDINGAREA4;
	}
	public String getBUILDINGAREA4INDICATOR() {
	return BUILDINGAREA4INDICATOR;
	}
	public void setBUILDINGAREA4INDICATOR(String bUILDINGAREA4INDICATOR) {
	BUILDINGAREA4INDICATOR = bUILDINGAREA4INDICATOR;
	}
	public String getBUILDINGAREA5() {
	return BUILDINGAREA5;
	}
	public void setBUILDINGAREA5(String bUILDINGAREA5) {
	BUILDINGAREA5 = bUILDINGAREA5;
	}
	public String getBUILDINGAREA5INDICATOR() {
	return BUILDINGAREA5INDICATOR;
	}
	public void setBUILDINGAREA5INDICATOR(String bUILDINGAREA5INDICATOR) {
	BUILDINGAREA5INDICATOR = bUILDINGAREA5INDICATOR;
	}
	public String getBUILDINGAREA6() {
	return BUILDINGAREA6;
	}
	public void setBUILDINGAREA6(String bUILDINGAREA6) {
	BUILDINGAREA6 = bUILDINGAREA6;
	}
	public String getBUILDINGAREA6INDICATOR() {
	return BUILDINGAREA6INDICATOR;
	}
	public void setBUILDINGAREA6INDICATOR(String bUILDINGAREA6INDICATOR) {
	BUILDINGAREA6INDICATOR = bUILDINGAREA6INDICATOR;
	}
	public String getBUILDINGAREA7() {
	return BUILDINGAREA7;
	}
	public void setBUILDINGAREA7(String bUILDINGAREA7) {
	BUILDINGAREA7 = bUILDINGAREA7;
	}
	public String getBUILDINGAREA7INDICATOR() {
	return BUILDINGAREA7INDICATOR;
	}
	public void setBUILDINGAREA7INDICATOR(String bUILDINGAREA7INDICATOR) {
	BUILDINGAREA7INDICATOR = bUILDINGAREA7INDICATOR;
	}
	public String getEFFECTIVEYEARBUILT() {
	return EFFECTIVEYEARBUILT;
	}
	public void setEFFECTIVEYEARBUILT(String eFFECTIVEYEARBUILT) {
	EFFECTIVEYEARBUILT = eFFECTIVEYEARBUILT;
	}
	public String getHEATINGFUELTYPE() {
	return HEATINGFUELTYPE;
	}
	public void setHEATINGFUELTYPE(String hEATINGFUELTYPE) {
	HEATINGFUELTYPE = hEATINGFUELTYPE;
	}
	public String getAIRCONDITIONINGTYPE() {
	return AIRCONDITIONINGTYPE;
	}
	public void setAIRCONDITIONINGTYPE(String aIRCONDITIONINGTYPE) {
	AIRCONDITIONINGTYPE = aIRCONDITIONINGTYPE;
	}
	public String getLOTSIZEACRES() {
	return LOTSIZEACRES;
	}
	public void setLOTSIZEACRES(String lOTSIZEACRES) {
	LOTSIZEACRES = lOTSIZEACRES;
	}
	public String getMORTGAGELENDERNAME() {
	return MORTGAGELENDERNAME;
	}
	public void setMORTGAGELENDERNAME(String mORTGAGELENDERNAME) {
	MORTGAGELENDERNAME = mORTGAGELENDERNAME;
	}
	public String getINTERIORWALLS() {
	return INTERIORWALLS;
	}
	public void setINTERIORWALLS(String iNTERIORWALLS) {
	INTERIORWALLS = iNTERIORWALLS;
	}
	public String getSCHOOLTAXDISTRICT1() {
	return SCHOOLTAXDISTRICT1;
	}
	public void setSCHOOLTAXDISTRICT1(String sCHOOLTAXDISTRICT1) {
	SCHOOLTAXDISTRICT1 = sCHOOLTAXDISTRICT1;
	}
	public String getSCHOOLTAXDISTRICT1INDICATOR() {
	return SCHOOLTAXDISTRICT1INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT1INDICATOR(String sCHOOLTAXDISTRICT1INDICATOR) {
	SCHOOLTAXDISTRICT1INDICATOR = sCHOOLTAXDISTRICT1INDICATOR;
	}
	public String getSCHOOLTAXDISTRICT2() {
	return SCHOOLTAXDISTRICT2;
	}
	public void setSCHOOLTAXDISTRICT2(String sCHOOLTAXDISTRICT2) {
	SCHOOLTAXDISTRICT2 = sCHOOLTAXDISTRICT2;
	}
	public String getSCHOOLTAXDISTRICT2INDICATOR() {
	return SCHOOLTAXDISTRICT2INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT2INDICATOR(String sCHOOLTAXDISTRICT2INDICATOR) {
	SCHOOLTAXDISTRICT2INDICATOR = sCHOOLTAXDISTRICT2INDICATOR;
	}
	public String getSCHOOLTAXDISTRICT3() {
	return SCHOOLTAXDISTRICT3;
	}
	public void setSCHOOLTAXDISTRICT3(String sCHOOLTAXDISTRICT3) {
	SCHOOLTAXDISTRICT3 = sCHOOLTAXDISTRICT3;
	}
	public String getSCHOOLTAXDISTRICT3INDICATOR() {
	return SCHOOLTAXDISTRICT3INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT3INDICATOR(String sCHOOLTAXDISTRICT3INDICATOR) {
	SCHOOLTAXDISTRICT3INDICATOR = sCHOOLTAXDISTRICT3INDICATOR;
	}
	public String getSITEINFLUENCE() {
	return SITEINFLUENCE;
	}
	public void setSITEINFLUENCE(String sITEINFLUENCE) {
	SITEINFLUENCE = sITEINFLUENCE;
	}
	public String getAMENITIES() {
	return AMENITIES;
	}
	public void setAMENITIES(String aMENITIES) {
	AMENITIES = aMENITIES;
	}
	public String getOTHERIMPRBUILDINGINDICATOR1() {
	return OTHERIMPRBUILDINGINDICATOR1;
	}
	public void setOTHERIMPRBUILDINGINDICATOR1(String oTHERIMPRBUILDINGINDICATOR1) {
	OTHERIMPRBUILDINGINDICATOR1 = oTHERIMPRBUILDINGINDICATOR1;
	}
	public String getOTHERIMPRBUILDINGINDICATOR2() {
	return OTHERIMPRBUILDINGINDICATOR2;
	}
	public void setOTHERIMPRBUILDINGINDICATOR2(String oTHERIMPRBUILDINGINDICATOR2) {
	OTHERIMPRBUILDINGINDICATOR2 = oTHERIMPRBUILDINGINDICATOR2;
	}
	public String getOTHERIMPRBUILDINGINDICATOR3() {
	return OTHERIMPRBUILDINGINDICATOR3;
	}
	public void setOTHERIMPRBUILDINGINDICATOR3(String oTHERIMPRBUILDINGINDICATOR3) {
	OTHERIMPRBUILDINGINDICATOR3 = oTHERIMPRBUILDINGINDICATOR3;
	}
	public String getOTHERIMPRBUILDINGINDICATOR4() {
	return OTHERIMPRBUILDINGINDICATOR4;
	}
	public void setOTHERIMPRBUILDINGINDICATOR4(String oTHERIMPRBUILDINGINDICATOR4) {
	OTHERIMPRBUILDINGINDICATOR4 = oTHERIMPRBUILDINGINDICATOR4;
	}
	public String getNEIGHBORHOODCODE() {
	return NEIGHBORHOODCODE;
	}
	public void setNEIGHBORHOODCODE(String nEIGHBORHOODCODE) {
	NEIGHBORHOODCODE = nEIGHBORHOODCODE;
	}
	public String getCONDOPROJECTBUILDINGNAME() {
	return CONDOPROJECTBUILDINGNAME;
	}
	public void setCONDOPROJECTBUILDINGNAME(String cONDOPROJECTBUILDINGNAME) {
	CONDOPROJECTBUILDINGNAME = cONDOPROJECTBUILDINGNAME;
	}
	public String getOTHERIMPRBUILDINGINDICATOR5() {
	return OTHERIMPRBUILDINGINDICATOR5;
	}
	public void setOTHERIMPRBUILDINGINDICATOR5(String oTHERIMPRBUILDINGINDICATOR5) {
	OTHERIMPRBUILDINGINDICATOR5 = oTHERIMPRBUILDINGINDICATOR5;
	}
	public String getAMENITIES2() {
	return AMENITIES2;
	}
	public void setAMENITIES2(String aMENITIES2) {
	AMENITIES2 = aMENITIES2;
	}
	public String getOTHERIMPRBUILDINGAREA1() {
	return OTHERIMPRBUILDINGAREA1;
	}
	public void setOTHERIMPRBUILDINGAREA1(String oTHERIMPRBUILDINGAREA1) {
	OTHERIMPRBUILDINGAREA1 = oTHERIMPRBUILDINGAREA1;
	}
	public String getOTHERIMPRBUILDINGAREA2() {
	return OTHERIMPRBUILDINGAREA2;
	}
	public void setOTHERIMPRBUILDINGAREA2(String oTHERIMPRBUILDINGAREA2) {
	OTHERIMPRBUILDINGAREA2 = oTHERIMPRBUILDINGAREA2;
	}
	public String getOTHERIMPRBUILDINGAREA3() {
	return OTHERIMPRBUILDINGAREA3;
	}
	public void setOTHERIMPRBUILDINGAREA3(String oTHERIMPRBUILDINGAREA3) {
	OTHERIMPRBUILDINGAREA3 = oTHERIMPRBUILDINGAREA3;
	}
	public String getOTHERIMPRBUILDINGAREA4() {
	return OTHERIMPRBUILDINGAREA4;
	}
	public void setOTHERIMPRBUILDINGAREA4(String oTHERIMPRBUILDINGAREA4) {
	OTHERIMPRBUILDINGAREA4 = oTHERIMPRBUILDINGAREA4;
	}
	public String getOTHERIMPRBUILDINGAREA5() {
	return OTHERIMPRBUILDINGAREA5;
	}
	public void setOTHERIMPRBUILDINGAREA5(String oTHERIMPRBUILDINGAREA5) {
	OTHERIMPRBUILDINGAREA5 = oTHERIMPRBUILDINGAREA5;
	}
	public String getOTHERROOMS() {
	return OTHERROOMS;
	}
	public void setOTHERROOMS(String oTHERROOMS) {
	OTHERROOMS = oTHERROOMS;
	}
	public String getEXTRAFEATURES1AREA() {
	return EXTRAFEATURES1AREA;
	}
	public void setEXTRAFEATURES1AREA(String eXTRAFEATURES1AREA) {
	EXTRAFEATURES1AREA = eXTRAFEATURES1AREA;
	}
	public String getEXTRAFEATURES1INDICATOR() {
	return EXTRAFEATURES1INDICATOR;
	}
	public void setEXTRAFEATURES1INDICATOR(String eXTRAFEATURES1INDICATOR) {
	EXTRAFEATURES1INDICATOR = eXTRAFEATURES1INDICATOR;
	}
	public String getTOPOGRAPHY() {
	return TOPOGRAPHY;
	}
	public void setTOPOGRAPHY(String tOPOGRAPHY) {
	TOPOGRAPHY = tOPOGRAPHY;
	}
	public String getROOFTYPE() {
	return ROOFTYPE;
	}
	public void setROOFTYPE(String rOOFTYPE) {
	ROOFTYPE = rOOFTYPE;
	}
	public String getEXTRAFEATURES2AREA() {
	return EXTRAFEATURES2AREA;
	}
	public void setEXTRAFEATURES2AREA(String eXTRAFEATURES2AREA) {
	EXTRAFEATURES2AREA = eXTRAFEATURES2AREA;
	}
	public String getEXTRAFEATURES2INDICATOR() {
	return EXTRAFEATURES2INDICATOR;
	}
	public void setEXTRAFEATURES2INDICATOR(String eXTRAFEATURES2INDICATOR) {
	EXTRAFEATURES2INDICATOR = eXTRAFEATURES2INDICATOR;
	}
	public String getEXTRAFEATURES3AREA() {
	return EXTRAFEATURES3AREA;
	}
	public void setEXTRAFEATURES3AREA(String eXTRAFEATURES3AREA) {
	EXTRAFEATURES3AREA = eXTRAFEATURES3AREA;
	}
	public String getEXTRAFEATURES3INDICATOR() {
	return EXTRAFEATURES3INDICATOR;
	}
	public void setEXTRAFEATURES3INDICATOR(String eXTRAFEATURES3INDICATOR) {
	EXTRAFEATURES3INDICATOR = eXTRAFEATURES3INDICATOR;
	}
	public String getEXTRAFEATURES4AREA() {
	return EXTRAFEATURES4AREA;
	}
	public void setEXTRAFEATURES4AREA(String eXTRAFEATURES4AREA) {
	EXTRAFEATURES4AREA = eXTRAFEATURES4AREA;
	}
	public String getEXTRAFEATURES4INDICATOR() {
	return EXTRAFEATURES4INDICATOR;
	}
	public void setEXTRAFEATURES4INDICATOR(String eXTRAFEATURES4INDICATOR) {
	EXTRAFEATURES4INDICATOR = eXTRAFEATURES4INDICATOR;
	}
	public String getOLDAPN() {
	return OLDAPN;
	}
	public void setOLDAPN(String oLDAPN) {
	OLDAPN = oLDAPN;
	}
	public String getBUILDINGCONDITION() {
	return BUILDINGCONDITION;
	}
	public void setBUILDINGCONDITION(String bUILDINGCONDITION) {
	BUILDINGCONDITION = bUILDINGCONDITION;
	}
	public String getLOTSIZEFRONTAGEFEET() {
	return LOTSIZEFRONTAGEFEET;
	}
	public void setLOTSIZEFRONTAGEFEET(String lOTSIZEFRONTAGEFEET) {
	LOTSIZEFRONTAGEFEET = lOTSIZEFRONTAGEFEET;
	}
	public String getLOTSIZEDEPTHFEET() {
	return LOTSIZEDEPTHFEET;
	}
	public void setLOTSIZEDEPTHFEET(String lOTSIZEDEPTHFEET) {
	LOTSIZEDEPTHFEET = lOTSIZEDEPTHFEET;
	}
	public String getCOMMENTS() {
	return COMMENTS;
	}
	public void setCOMMENTS(String cOMMENTS) {
	COMMENTS = cOMMENTS;
	}
	public String getWATER() {
	return WATER;
	}
	public void setWATER(String wATER) {
	WATER = wATER;
	}
	public String getSEWER() {
	return SEWER;
	}
	public void setSEWER(String sEWER) {
	SEWER = sEWER;
	}
	public String getNEWRECORDTYPE() {
	return NEWRECORDTYPE;
	}
	public void setNEWRECORDTYPE(String nEWRECORDTYPE) {
	NEWRECORDTYPE = nEWRECORDTYPE;
	} 
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}
	}

