package com.appstek.dc.util;

import java.util.HashMap;
import java.util.Map;

import com.sun.xml.internal.ws.policy.privateutil.PolicyUtils.Collections;

public class RecordTypeTableConstant {
public static String STATEPOSTALCODE ="STATEPOSTALCODE varchar(500) DEFAULT NULL ";
public static String COUNTYNAME ="COUNTYNAME varchar(500) DEFAULT NULL ";
public static String APNORPINNUMBER ="APNORPINNUMBER varchar(500) DEFAULT NULL ";
public static String DUPLICATEAPNMULTIADDRESSID ="DUPLICATEAPNMULTIADDRESSID varchar(500) DEFAULT NULL ";
public static String PROPADDRSRCEFLAG ="PROPADDRSRCEFLAG varchar(500) DEFAULT NULL ";
public static String PROPHOUSENUMBER ="PROPHOUSENUMBER varchar(500) DEFAULT NULL ";
public static String PROPHOUSEALPHA ="PROPHOUSEALPHA varchar(500) DEFAULT NULL ";
public static String PROPSTREETDIRECTIONLEFT ="PROPSTREETDIRECTIONLEFT varchar(500) DEFAULT NULL ";
public static String PROPSTREETNAME ="PROPSTREETNAME varchar(500) DEFAULT NULL ";
public static String PROPSTREETSUFFIX ="PROPSTREETSUFFIX varchar(500) DEFAULT NULL ";
public static String PROPSTREETDIRECTIONRIGHT ="PROPSTREETDIRECTIONRIGHT varchar(500) DEFAULT NULL ";
public static String PROPUNITNUMBER ="PROPUNITNUMBER varchar(500) DEFAULT NULL ";
public static String PROPFULLSTREETADDRESS ="PROPFULLSTREETADDRESS varchar(500) DEFAULT NULL ";
public static String PROPCITYNAME ="PROPCITYNAME varchar(500) DEFAULT NULL ";
public static String PROPSTATE ="PROPSTATE varchar(500) DEFAULT NULL ";
public static String PROPZIPCODE ="PROPZIPCODE varchar(500) DEFAULT NULL ";
public static String PROPZIP4 ="PROPZIP4 varchar(500) DEFAULT NULL ";
public static String ASSESSEEOWNERNAME ="ASSESSEEOWNERNAME varchar(500) DEFAULT NULL ";
public static String SECOND_ASSESSEEOWNERNAME ="SECOND_ASSESSEEOWNERNAME varchar(500) DEFAULT NULL ";
public static String ASSEVESTINGIDCODE ="ASSEVESTINGIDCODE varchar(500) DEFAULT NULL ";
public static String TAXACCOUNTNUMBER ="TAXACCOUNTNUMBER varchar(500) DEFAULT NULL ";
public static String ASSEMAILCAREOFNAME ="ASSEMAILCAREOFNAME varchar(500) DEFAULT NULL ";
public static String ASSEMAILHOUSENUMBER ="ASSEMAILHOUSENUMBER varchar(150) DEFAULT NULL ";
public static String ASSEMAILHOUSEALPHA ="ASSEMAILHOUSEALPHA varchar(500) DEFAULT NULL ";
public static String ASSEMAILSTREETDIRECTIONLEFT ="ASSEMAILSTREETDIRECTIONLEFT varchar(500) DEFAULT NULL ";
public static String ASSEMAILSTREETNAME ="ASSEMAILSTREETNAME varchar(500) DEFAULT NULL ";
public static String ASSEMAILSTREETSUFFIX ="ASSEMAILSTREETSUFFIX varchar(500) DEFAULT NULL ";
public static String ASSEMAILSTREETDIRECTIONRIGHT ="ASSEMAILSTREETDIRECTIONRIGHT varchar(500) DEFAULT NULL ";
public static String ASSEMAILUNITNUMBER ="ASSEMAILUNITNUMBER varchar(500) DEFAULT NULL ";
public static String ASSEMAILFULLSTREETADDRESS ="ASSEMAILFULLSTREETADDRESS varchar(500) DEFAULT NULL ";
public static String ASSEMAILCITYNAME ="ASSEMAILCITYNAME varchar(500) DEFAULT NULL ";
public static String ASSEMAILSTATE ="ASSEMAILSTATE varchar(500) DEFAULT NULL ";
public static String ASSEMAILZIPCODE ="ASSEMAILZIPCODE varchar(500) DEFAULT NULL ";
public static String ASSEMAILZIP4 ="ASSEMAILZIP4 varchar(500) DEFAULT NULL ";
public static String STATELANDUSECODE ="STATELANDUSECODE varchar(500) DEFAULT NULL ";
public static String OWNEROCCUPIEDSFRCONDO ="OWNEROCCUPIEDSFRCONDO varchar(500) DEFAULT NULL ";
public static String ASSESSEDLANDVALUE ="ASSESSEDLANDVALUE varchar(500) DEFAULT NULL ";
public static String ASSESSEDIMPROVEMENTVALUE ="ASSESSEDIMPROVEMENTVALUE varchar(500) DEFAULT NULL ";
public static String TOTALASSESSEDVALUE ="TOTALASSESSEDVALUE varchar(500) DEFAULT NULL ";
public static String ASSESSMENTYEAR ="ASSESSMENTYEAR varchar(500) DEFAULT NULL ";
public static String CALIFHOMEOWNERSEXEMPTION ="CALIFHOMEOWNERSEXEMPTION varchar(500) DEFAULT NULL ";
public static String TAXEXEMPTIONCODE ="TAXEXEMPTIONCODE varchar(500) DEFAULT NULL ";
public static String TAXRATECODEAREA ="TAXRATECODEAREA varchar(500) DEFAULT NULL ";
public static String TAXAMOUNT ="TAXAMOUNT varchar(500) DEFAULT NULL ";
public static String TAXYEAR ="TAXYEAR varchar(500) DEFAULT NULL ";
public static String TAXDELINQUENTYEAR ="TAXDELINQUENTYEAR varchar(500) DEFAULT NULL ";
public static String RECORDERSDOCUMENTNUMBER ="RECORDERSDOCUMENTNUMBER varchar(500) DEFAULT NULL ";
public static String RECORDERSBOOKNUMBER ="RECORDERSBOOKNUMBER varchar(500) DEFAULT NULL ";
public static String RECORDERSPAGENUMBER ="RECORDERSPAGENUMBER varchar(500) DEFAULT NULL ";
public static String RECORDINGDATE ="RECORDINGDATE varchar(500) DEFAULT NULL ";
public static String DOCUMENTTYPECOUNTYDESCRIPTION ="DOCUMENTTYPECOUNTYDESCRIPTION varchar(500) DEFAULT NULL ";
public static String SALESPRICE ="SALESPRICE varchar(500) DEFAULT NULL ";
public static String SALESPRICECODE ="SALESPRICECODE varchar(500) DEFAULT NULL ";
public static String PRIORSALEDATE ="PRIORSALEDATE varchar(500) DEFAULT NULL ";
public static String PRIORSALESPRICE ="PRIORSALESPRICE varchar(500) DEFAULT NULL ";
public static String PRIORSALESCODE ="PRIORSALESCODE varchar(500) DEFAULT NULL ";
public static String LEGALLOTCODE ="LEGALLOTCODE varchar(500) DEFAULT NULL ";
public static String LEGALLOTNUMBER ="LEGALLOTNUMBER varchar(500) DEFAULT NULL ";
public static String LEGALLANDLOT ="LEGALLANDLOT varchar(500) DEFAULT NULL ";
public static String LEGALBLOCK ="LEGALBLOCK varchar(500) DEFAULT NULL ";
public static String LEGALSECTION ="LEGALSECTION varchar(500) DEFAULT NULL ";
public static String LEGALDISTRICT ="LEGALDISTRICT varchar(500) DEFAULT NULL ";
public static String LEGALUNIT ="LEGALUNIT varchar(500) DEFAULT NULL ";
public static String LEGALCITYMUNICIPALITYTOWNSHIP ="LEGALCITYMUNICIPALITYTOWNSHIP varchar(500) DEFAULT NULL ";
public static String LEGALSUBDIVISIONNAME ="LEGALSUBDIVISIONNAME varchar(500) DEFAULT NULL ";
public static String LEGALPHASENO ="LEGALPHASENO varchar(500) DEFAULT NULL ";
public static String LEGALTRACTNO ="LEGALTRACTNO varchar(500) DEFAULT NULL ";
public static String LEGALSECTWPRNGMER ="LEGALSECTWPRNGMER varchar(500) DEFAULT NULL ";
public static String LEGALBRIEFDESCRIPTION ="LEGALBRIEFDESCRIPTION varchar(200) DEFAULT NULL ";
public static String LEGALASSESSORSMAPREF ="LEGALASSESSORSMAPREF varchar(500) DEFAULT NULL ";
public static String COUNTYLANDUSEDESCRIPTION ="COUNTYLANDUSEDESCRIPTION varchar(500) DEFAULT NULL ";
public static String COUNTYLANDUSECODE ="COUNTYLANDUSECODE varchar(500) DEFAULT NULL ";
public static String STANDARDIZEDLANDUSECODE ="STANDARDIZEDLANDUSECODE varchar(500) DEFAULT NULL ";
public static String TIMESHARECODE ="TIMESHARECODE varchar(500) DEFAULT NULL ";
public static String ZONING ="ZONING varchar(500) DEFAULT NULL ";
public static String LOTSIZEORAREA ="LOTSIZEORAREA varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA ="BUILDINGAREA varchar(500) DEFAULT NULL ";
public static String YEARBUILT ="YEARBUILT varchar(500) DEFAULT NULL ";
public static String NOOFBUILDINGS ="NOOFBUILDINGS varchar(500) DEFAULT NULL ";
public static String NOOFSTORIES ="NOOFSTORIES varchar(500) DEFAULT NULL ";
public static String NOOFUNITS ="NOOFUNITS varchar(500) DEFAULT NULL ";
public static String TOTALNOOFROOMS ="TOTALNOOFROOMS varchar(500) DEFAULT NULL ";
public static String NOOFBEDROOMS ="NOOFBEDROOMS varchar(500) DEFAULT NULL ";
public static String NOOFBATHS ="NOOFBATHS varchar(500) DEFAULT NULL ";
public static String NOOFPARTIALBATHS ="NOOFPARTIALBATHS varchar(500) DEFAULT NULL ";
public static String GARAGETYPEPARKING ="GARAGETYPEPARKING varchar(500) DEFAULT NULL ";
public static String PARKINGNUMBEROFCARS ="PARKINGNUMBEROFCARS varchar(500) DEFAULT NULL ";
public static String POOL ="POOL varchar(500) DEFAULT NULL ";
public static String MAILCITYSTZIP ="MAILCITYSTZIP varchar(500) DEFAULT NULL ";
public static String FIPSCODE ="FIPSCODE varchar(500) DEFAULT NULL ";
public static String TAPECUTDATE ="TAPECUTDATE varchar(500) DEFAULT NULL ";
public static String CENSUSTRACT ="CENSUSTRACT varchar(500) DEFAULT NULL ";
public static String RECORDTYPE ="RECORDTYPE varchar(500) DEFAULT NULL ";
public static String MARKETVALUELAND ="MARKETVALUELAND varchar(500) DEFAULT NULL ";
public static String MARKETVALUEIMPROVEMENT ="MARKETVALUEIMPROVEMENT varchar(500) DEFAULT NULL ";
public static String TOTALMARKETVALUE ="TOTALMARKETVALUE varchar(500) DEFAULT NULL ";
public static String MARKETVALUEYEAR ="MARKETVALUEYEAR varchar(500) DEFAULT NULL ";
public static String BUILDINGCLASS ="BUILDINGCLASS varchar(500) DEFAULT NULL ";
public static String STYLE ="STYLE varchar(500) DEFAULT NULL ";
public static String TYPECONSTRUCTION ="TYPECONSTRUCTION varchar(500) DEFAULT NULL ";
public static String EXTERIORWALLS ="EXTERIORWALLS varchar(500) DEFAULT NULL ";
public static String FOUNDATION ="FOUNDATION varchar(500) DEFAULT NULL ";
public static String ROOFCOVER ="ROOFCOVER varchar(500) DEFAULT NULL ";
public static String HEATING ="HEATING varchar(500) DEFAULT NULL ";
public static String AIRCONDITIONING ="AIRCONDITIONING varchar(500) DEFAULT NULL ";
public static String ELEVATOR ="ELEVATOR varchar(500) DEFAULT NULL ";
public static String FIREPLACE ="FIREPLACE varchar(500) DEFAULT NULL ";
public static String BASEMENT ="BASEMENT varchar(500) DEFAULT NULL ";
public static String EDITIONNUMBER ="EDITIONNUMBER varchar(500) DEFAULT NULL ";
public static String PROPERTYCOUNTRYCODE ="PROPERTYCOUNTRYCODE varchar(500) DEFAULT NULL ";
public static String BUILDINGAREAINDICATOR ="BUILDINGAREAINDICATOR varchar(500) DEFAULT NULL ";
public static String PROPADDRMATCHCODE ="PROPADDRMATCHCODE varchar(500) DEFAULT NULL ";
public static String PROPADDRUNITDESIGNATOR ="PROPADDRUNITDESIGNATOR varchar(500) DEFAULT NULL ";
public static String PROPADDRUNITNUMBER ="PROPADDRUNITNUMBER varchar(500) DEFAULT NULL ";
public static String PROPADDRCARRIERROUTE ="PROPADDRCARRIERROUTE varchar(500) DEFAULT NULL ";
public static String PROPADDRGEOCODEMATCHCODE ="PROPADDRGEOCODEMATCHCODE varchar(500) DEFAULT NULL ";
public static String PROPADDRLATITUDE ="PROPADDRLATITUDE varchar(500) DEFAULT NULL ";
public static String PROPADDRLONGITUDE ="PROPADDRLONGITUDE varchar(500) DEFAULT NULL ";
public static String PROPADDRCENSUSTRACTBLOCK ="PROPADDRCENSUSTRACTBLOCK varchar(500) DEFAULT NULL ";
public static String MAILADDRMATCHCODE ="MAILADDRMATCHCODE varchar(500) DEFAULT NULL ";
public static String MAILADDRUNITDESIGNATOR ="MAILADDRUNITDESIGNATOR varchar(500) DEFAULT NULL ";
public static String MAILADDRUNITNUMBER ="MAILADDRUNITNUMBER varchar(500) DEFAULT NULL ";
public static String MAILADDRCARRIERROUTE ="MAILADDRCARRIERROUTE varchar(500) DEFAULT NULL ";
public static String ASSESSEEOWNERNAMEINDICATOR ="ASSESSEEOWNERNAMEINDICATOR varchar(500) DEFAULT NULL ";
public static String SECOND_ASSESSEEOWNER_INDICATOR ="SECOND_ASSESSEEOWNER_INDICATOR varchar(500) DEFAULT NULL ";
public static String MAILCAREOFNAMEINDICATOR ="MAILCAREOFNAMEINDICATOR varchar(500) DEFAULT NULL ";
public static String ASSESSEEOWNERNAMETYPE ="ASSESSEEOWNERNAMETYPE varchar(500) DEFAULT NULL ";
public static String SECONDASSESSEEOWNERNAMETYPE ="SECONDASSESSEEOWNERNAMETYPE varchar(500) DEFAULT NULL ";
public static String ALTOLDAPNINDICATOR ="ALTOLDAPNINDICATOR varchar(500) DEFAULT NULL ";
public static String CERTIFICATIONDATE ="CERTIFICATIONDATE varchar(500) DEFAULT NULL ";
public static String LOTSIZESQFT ="LOTSIZESQFT varchar(500) DEFAULT NULL ";
public static String BUILDINGQUALITY ="BUILDINGQUALITY varchar(500) DEFAULT NULL ";
public static String FLOORCOVER ="FLOORCOVER varchar(500) DEFAULT NULL ";
public static String NOOFPLUMBINGFIXTURES ="NOOFPLUMBINGFIXTURES varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA1 ="BUILDINGAREA1 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA1INDICATOR ="BUILDINGAREA1INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA2 ="BUILDINGAREA2 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA2INDICATOR ="BUILDINGAREA2INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA3 ="BUILDINGAREA3 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA3INDICATOR ="BUILDINGAREA3INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA4 ="BUILDINGAREA4 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA4INDICATOR ="BUILDINGAREA4INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA5 ="BUILDINGAREA5 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA5INDICATOR ="BUILDINGAREA5INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA6 ="BUILDINGAREA6 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA6INDICATOR ="BUILDINGAREA6INDICATOR varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA7 ="BUILDINGAREA7 varchar(500) DEFAULT NULL ";
public static String BUILDINGAREA7INDICATOR ="BUILDINGAREA7INDICATOR varchar(500) DEFAULT NULL ";
public static String EFFECTIVEYEARBUILT ="EFFECTIVEYEARBUILT varchar(500) DEFAULT NULL ";
public static String HEATINGFUELTYPE ="HEATINGFUELTYPE varchar(500) DEFAULT NULL ";
public static String AIRCONDITIONINGTYPE ="AIRCONDITIONINGTYPE varchar(500) DEFAULT NULL ";
public static String LOTSIZEACRES ="LOTSIZEACRES varchar(500) DEFAULT NULL ";
public static String MORTGAGELENDERNAME ="MORTGAGELENDERNAME varchar(500) DEFAULT NULL ";
public static String INTERIORWALLS ="INTERIORWALLS varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT1 ="SCHOOLTAXDISTRICT1 varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT1INDICATOR ="SCHOOLTAXDISTRICT1INDICATOR varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT2 ="SCHOOLTAXDISTRICT2 varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT2INDICATOR ="SCHOOLTAXDISTRICT2INDICATOR varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT3 ="SCHOOLTAXDISTRICT3 varchar(500) DEFAULT NULL ";
public static String SCHOOLTAXDISTRICT3INDICATOR ="SCHOOLTAXDISTRICT3INDICATOR varchar(500) DEFAULT NULL ";
public static String SITEINFLUENCE ="SITEINFLUENCE varchar(500) DEFAULT NULL ";
public static String AMENITIES ="AMENITIES varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGINDICATOR1 ="OTHERIMPRBUILDINGINDICATOR1 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGINDICATOR2 ="OTHERIMPRBUILDINGINDICATOR2 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGINDICATOR3 ="OTHERIMPRBUILDINGINDICATOR3 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGINDICATOR4 ="OTHERIMPRBUILDINGINDICATOR4 varchar(500) DEFAULT NULL ";
public static String NEIGHBORHOODCODE ="NEIGHBORHOODCODE varchar(500) DEFAULT NULL ";
public static String CONDOPROJECTBUILDINGNAME ="CONDOPROJECTBUILDINGNAME varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGINDICATOR5 ="OTHERIMPRBUILDINGINDICATOR5 varchar(500) DEFAULT NULL ";
public static String AMENITIES2 ="AMENITIES2 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGAREA1 ="OTHERIMPRBUILDINGAREA1 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGAREA2 ="OTHERIMPRBUILDINGAREA2 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGAREA3 ="OTHERIMPRBUILDINGAREA3 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGAREA4 ="OTHERIMPRBUILDINGAREA4 varchar(500) DEFAULT NULL ";
public static String OTHERIMPRBUILDINGAREA5 ="OTHERIMPRBUILDINGAREA5 varchar(500) DEFAULT NULL ";
public static String OTHERROOMS ="OTHERROOMS varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES1AREA ="EXTRAFEATURES1AREA varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES1INDICATOR ="EXTRAFEATURES1INDICATOR varchar(500) DEFAULT NULL ";
public static String TOPOGRAPHY ="TOPOGRAPHY varchar(500) DEFAULT NULL ";
public static String ROOFTYPE ="ROOFTYPE varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES2AREA ="EXTRAFEATURES2AREA varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES2INDICATOR ="EXTRAFEATURES2INDICATOR varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES3AREA ="EXTRAFEATURES3AREA varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES3INDICATOR ="EXTRAFEATURES3INDICATOR varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES4AREA ="EXTRAFEATURES4AREA varchar(500) DEFAULT NULL ";
public static String EXTRAFEATURES4INDICATOR ="EXTRAFEATURES4INDICATOR varchar(500) DEFAULT NULL ";
public static String OLDAPN ="OLDAPN varchar(500) DEFAULT NULL ";
public static String BUILDINGCONDITION ="BUILDINGCONDITION varchar(500) DEFAULT NULL ";
public static String LOTSIZEFRONTAGEFEET ="LOTSIZEFRONTAGEFEET varchar(500) DEFAULT NULL ";
public static String LOTSIZEDEPTHFEET ="LOTSIZEDEPTHFEET varchar(500) DEFAULT NULL ";
public static String COMMENTS ="COMMENTS varchar(500) DEFAULT NULL ";
public static String WATER ="WATER varchar(500) DEFAULT NULL ";
public static String SEWER ="SEWER varchar(500) DEFAULT NULL ";
public static String NEWRECORDTYPE ="NEWRECORDTYPE varchar(500) DEFAULT NULL ";

/*public static Map<String,String> realMap1 = new HashMap<String, String>() {
	{
		 put("STATEPOSTALCODE","F1");
		 put("COUNTYNAME","F2");
		 put("APNORPINNUMBER","3");
		 put("DUPLICATEAPNMULTIADDRESSID","4");
		 put("PROPADDRSRCEFLAG","5");
		 put("PROPHOUSENUMBER","6");
		 put("PROPHOUSEALPHA","7");
		 put("PROPSTREETDIRECTIONLEFT","8");
		 put("PROPSTREETNAME","9");
		 put("PROPSTREETSUFFIX","10");
		 put("PROPSTREETDIRECTIONRIGHT","11");
		 put("PROPUNITNUMBER","12");
		 put("PROPFULLSTREETADDRESS","13");
		 put("PROPCITYNAME","14");
		 put("PROPSTATE","15");
		 put("PROPZIPCODE","16");
		 put("PROPZIP4","17");
		 put("ASSESSEEOWNERNAME","");
		 put("SECOND_ASSESSEEOWNERNAME","");
		 put("ASSEVESTINGIDCODE","");
		 put("TAXACCOUNTNUMBER","");
		 put("ASSEMAILCAREOFNAME","");
		 put("ASSEMAILHOUSENUMBER","");
		 put("ASSEMAILHOUSEALPHA","");
		 put("ASSEMAILSTREETDIRECTIONLEFT","");
		 put("ASSEMAILSTREETNAME","");
		 put("ASSEMAILSTREETSUFFIX","");
		 put("ASSEMAILSTREETDIRECTIONRIGHT","");
		 put("ASSEMAILUNITNUMBER","");
		 put("ASSEMAILFULLSTREETADDRESS","");
		 put("ASSEMAILCITYNAME","");
		 put("ASSEMAILSTATE","");
		 put("ASSEMAILZIPCODE","");
		 put("ASSEMAILZIP4","");
		 put("STATELANDUSECODE","");
		 put("OWNEROCCUPIEDSFRCONDO","");
		 put("ASSESSEDLANDVALUE","");
		 put("ASSESSEDIMPROVEMENTVALUE","");
		 put("TOTALASSESSEDVALUE","");
		 put("ASSESSMENTYEAR","");
		 put("CALIFHOMEOWNERSEXEMPTION","");
		 put("TAXEXEMPTIONCODE","");
		 put("TAXRATECODEAREA","");
		 put("TAXAMOUNT","");
		 put("TAXYEAR","");
		 put("TAXDELINQUENTYEAR","");
		 put("RECORDERSDOCUMENTNUMBER","");
		 put("RECORDERSBOOKNUMBER","");
		 put("RECORDERSPAGENUMBER","");
		 put("RECORDINGDATE","");
		 put("DOCUMENTTYPECOUNTYDESCRIPTION","");
		 put("SALESPRICE","");
		 put("SALESPRICECODE","");
		 put("PRIORSALEDATE","");
		 put("PRIORSALESPRICE","");
		 put("PRIORSALESCODE","");
		 put("LEGALLOTCODE","");
		 put("LEGALLOTNUMBER","");
		 put("LEGALLANDLOT","");
		 put("LEGALBLOCK","");
		 put("LEGALSECTION","");
		 put("LEGALDISTRICT","");
		 put("LEGALUNIT","");
		 put("LEGALCITYMUNICIPALITYTOWNSHIP","");
		 put("LEGALSUBDIVISIONNAME","");
		 put("LEGALPHASENO","");
		 put("LEGALTRACTNO","");
		 put("LEGALSECTWPRNGMER","");
		 put("LEGALBRIEFDESCRIPTION","");
		 put("LEGALASSESSORSMAPREF","");
		 put("COUNTYLANDUSEDESCRIPTION","");
		 put("COUNTYLANDUSECODE","");
		 put("STANDARDIZEDLANDUSECODE","");
		 put("TIMESHARECODE","");
		 put("ZONING","");
		 put("LOTSIZEORAREA","");
		 put("BUILDINGAREA","");
		 put("YEARBUILT","");
		 put("NOOFBUILDINGS","");
		 put("NOOFSTORIES","");
		 put("NOOFUNITS","");
		 put("TOTALNOOFROOMS","");
		 put("NOOFBEDROOMS","");
		 put("NOOFBATHS","");
		 put("NOOFPARTIALBATHS","");
		 put("GARAGETYPEPARKING","");
		 put("PARKINGNUMBEROFCARS","");
		 put("POOL","");
		 put("MAILCITYSTZIP","");
		 put("FIPSCODE","");
		 put("TAPECUTDATE","");
		 put("CENSUSTRACT","");
		 put("RECORDTYPE","");
		 put("MARKETVALUELAND","");
		 put("MARKETVALUEIMPROVEMENT","");
		 put("TOTALMARKETVALUE","");
		 put("MARKETVALUEYEAR","");
		 put("BUILDINGCLASS","");
		 put("STYLE","");
		 put("TYPECONSTRUCTION","");
		 put("EXTERIORWALLS","");
		 put("FOUNDATION","");
		 put("ROOFCOVER","");
		 put("HEATING","");
		 put("AIRCONDITIONING","");
		 put("ELEVATOR","");
		 put("FIREPLACE","");
		 put("BASEMENT","");
		 put("EDITIONNUMBER","");
		 put("PROPERTYCOUNTRYCODE","");
		 put("BUILDINGAREAINDICATOR","");
		 put("PROPADDRMATCHCODE","");
		 put("PROPADDRUNITDESIGNATOR","");
		 put("PROPADDRUNITNUMBER","");
		 put("PROPADDRCARRIERROUTE","");
		 put("PROPADDRGEOCODEMATCHCODE","");
		 put("PROPADDRLATITUDE","");
		 put("PROPADDRLONGITUDE","");
		 put("PROPADDRCENSUSTRACTBLOCK","");
		 put("MAILADDRMATCHCODE","");
		 put("MAILADDRUNITDESIGNATOR","");
		 put("MAILADDRUNITNUMBER","");
		 put("MAILADDRCARRIERROUTE","");
		 put("ASSESSEEOWNERNAMEINDICATOR","");
		 put("SECOND_ASSESSEEOWNER_INDICATOR","");
		 put("MAILCAREOFNAMEINDICATOR","");
		 put("ASSESSEEOWNERNAMETYPE","");
		 put("SECONDASSESSEEOWNERNAMETYPE","");
		 put("ALTOLDAPNINDICATOR","");
		 put("CERTIFICATIONDATE","");
		 put("LOTSIZESQFT","");
		 put("BUILDINGQUALITY","");
		 put("FLOORCOVER","");
		 put("NOOFPLUMBINGFIXTURES","");
		 put("BUILDINGAREA1","");
		 put("BUILDINGAREA1INDICATOR","");
		 put("BUILDINGAREA2","");
		 put("BUILDINGAREA2INDICATOR","");
		 put("BUILDINGAREA3","");
		 put("BUILDINGAREA3INDICATOR","");
		 put("BUILDINGAREA4","");
		 put("BUILDINGAREA4INDICATOR","");
		 put("BUILDINGAREA5","");
		 put("BUILDINGAREA5INDICATOR","");
		 put("BUILDINGAREA6","");
		 put("BUILDINGAREA6INDICATOR","");
		 put("BUILDINGAREA7","");
		 put("BUILDINGAREA7INDICATOR","");
		 put("EFFECTIVEYEARBUILT","");
		 put("HEATINGFUELTYPE","");
		 put("AIRCONDITIONINGTYPE","");
		 put("LOTSIZEACRES","");
		 put("MORTGAGELENDERNAME","");
		 put("INTERIORWALLS","");
		 put("SCHOOLTAXDISTRICT1","");
		 put("SCHOOLTAXDISTRICT1INDICATOR","");
		 put("SCHOOLTAXDISTRICT2","");
		 put("SCHOOLTAXDISTRICT2INDICATOR","");
		 put("SCHOOLTAXDISTRICT3","");
		 put("SCHOOLTAXDISTRICT3INDICATOR","");
		 put("SITEINFLUENCE","");
		 put("AMENITIES","");
		 put("OTHERIMPRBUILDINGINDICATOR1","");
		 put("OTHERIMPRBUILDINGINDICATOR2","");
		 put("OTHERIMPRBUILDINGINDICATOR3","");
		 put("OTHERIMPRBUILDINGINDICATOR4","");
		 put("NEIGHBORHOODCODE","");
		 put("CONDOPROJECTBUILDINGNAME","");
		 put("OTHERIMPRBUILDINGINDICATOR5","");
		 put("AMENITIES2","");
		 put("OTHERIMPRBUILDINGAREA1","");
		 put("OTHERIMPRBUILDINGAREA2","");
		 put("OTHERIMPRBUILDINGAREA3","");
		 put("OTHERIMPRBUILDINGAREA4","");
		 put("OTHERIMPRBUILDINGAREA5","");
		 put("OTHERROOMS","");
		 put("EXTRAFEATURES1AREA","");
		 put("EXTRAFEATURES1INDICATOR","");
		 put("TOPOGRAPHY","");
		 put("ROOFTYPE","");
		 put("EXTRAFEATURES2AREA","");
		 put("EXTRAFEATURES2INDICATOR","");
		 put("EXTRAFEATURES3AREA","");
		 put("EXTRAFEATURES3INDICATOR","");
		 put("EXTRAFEATURES4AREA","");
		 put("EXTRAFEATURES4INDICATOR","");
		 put("OLDAPN","");
		 put("BUILDINGCONDITION","");
		 put("LOTSIZEFRONTAGEFEET","");
		 put("LOTSIZEDEPTHFEET","");
		 put("COMMENTS","");
		 put("WATER","");
		 put("SEWER","");
		 put("NEWRECORDTYPE","");
	}
	};*/
	
	/*public Map<String,String> realMap = new HashMap<String, String>() {
		{
			 put("Field_1","");
			 put("Field_2","");
			 put("Field_3","");
			 put("Field_4","");
			 put("Field_5","");
			 put("Field_6","");
			 put("Field_7","");
			 put("Field_8","");
			 put("Field_9","");
			 put("Field_10","");
			 put("Field_11","");
			 put("Field_12","");
			 put("Field_13","");
			 put("Field_14","");
			 put("Field_15","");
			 put("Field_16","");
			 put("Field_17","");
			 put("Field_18","");
			 put("Field_19","");
			 put("Field_20","");
			 put("Field_21","");
			 put("Field_22","");
			 put("Field_23","");
			 put("Field_24","");
			 put("Field_25","");
			 put("Field_26","");
			 put("Field_27","");
			 put("Field_28","");
			 put("Field_29","");
			 put("Field_30","");
			 put("Field_31","");
			 put("Field_32","");
			 put("Field_33","");
			 put("Field_34","");
			 put("Field_35","");
			 put("Field_36","");
			 put("Field_37","");
			 put("Field_38","");
			 put("Field_39","");
			 put("Field_40","");
			 put("Field_41","");
			 put("Field_42","");
			 put("Field_43","");
			 put("Field_44","");
			 put("Field_45","");
			 put("Field_46","");
			 put("Field_47","");
			 put("Field_48","");
			 put("Field_49","");
			 put("Field_50","");
			 put("Field_51","");
			 put("Field_52","");
			 put("Field_53","");
			 put("Field_54","");
			 put("Field_55","");
			 put("Field_56","");
			 put("Field_57","");
			 put("Field_58","");
			 put("Field_59","");
			 put("Field_60","");
			 put("Field_61","");
			 put("Field_62","");
			 put("Field_63","");
			 put("Field_64","");
			 put("Field_65","");
			 put("Field_66","");
			 put("Field_67","");
			 put("Field_68","");
			 put("Field_69","");
			 put("Field_70","");
			 put("Field_71","");
			 put("Field_72","");
			 put("Field_73","");
			 put("Field_74","");
			 put("Field_75","");
			 put("Field_76","");
			 put("Field_77","");
			 put("Field_78","");
			 put("Field_79","");
			 put("Field_80","");
			 put("Field_81","");
			 put("Field_82","");
			 put("Field_83","");
			 put("Field_84","");
			 put("Field_85","");
			 put("Field_86","");
			 put("Field_87","");
			 put("Field_88","");
			 put("Field_89","");
			 put("Field_90","");
			 put("Field_91","");
			 put("Field_92","");
			 put("Field_93","");
			 put("Field_94","");
			 put("Field_95","");
			 put("Field_96","");
			 put("Field_97","");
			 put("Field_98","");
			 put("Field_99","");
			 put("Field_100","");
			 put("Field_101","");
			 put("Field_102","");
			 put("Field_103","");
			 put("Field_104","");
			 put("Field_105","");
			 put("Field_106","");
			 put("Field_107","");
			 put("Field_108","");
			 put("Field_109","");
			 put("Field_110","");
			 put("Field_111","");
			 put("Field_112","");
			 put("Field_113","");
			 put("Field_114","");
			 put("Field_115","");
			 put("Field_116","");
			 put("Field_117","");
			 put("Field_118","");
			 put("Field_119","");
			 put("Field_120","");
			 put("Field_121","");
			 put("Field_122","");
			 put("Field_123","");
			 put("Field_124","");
			 put("Field_125","");
			 put("Field_126","");
			 put("Field_127","");
			 put("Field_128","");
			 put("Field_129","");
			 put("Field_130","");
			 put("Field_131","");
			 put("Field_132","");
			 put("Field_133","");
			 put("Field_134","");
			 put("Field_135","");
			 put("Field_136","");
			 put("Field_137","");
			 put("Field_138","");
			 put("Field_139","");
			 put("Field_140","");
			 put("Field_141","");
			 put("Field_142","");
			 put("Field_143","");
			 put("Field_144","");
			 put("Field_145","");
			 put("Field_146","");
			 put("Field_147","");
			 put("Field_148","");
			 put("Field_149","");
			 put("Field_150","");
			 put("Field_151","");
			 put("Field_152","");
			 put("Field_153","");
			 put("Field_154","");
			 put("Field_155","");
			 put("Field_156","");
			 put("Field_157","");
			 put("Field_158","");
			 put("Field_159","");
			 put("Field_160","");
			 put("Field_161","");
			 put("Field_162","");
			 put("Field_163","");
			 put("Field_164","");
			 put("Field_165","");
			 put("Field_166","");
			 put("Field_167","");
			 put("Field_168","");
			 put("Field_169","");
			 put("Field_170","");
			 put("Field_171","");
			 put("Field_172","");
			 put("Field_173","");
			 put("Field_174","");
			 put("Field_175","");
			 put("Field_176","");
			 put("Field_177","");
			 put("Field_178","");
			 put("Field_179","");
			 put("Field_180","");
			 put("Field_181","");
			 put("Field_182","");
			 put("Field_183","");
			 put("Field_184","");
			 put("Field_185","");
			 put("Field_186","");
			 put("Field_187","");
			 put("Field_188","");
			 put("Field_189","");
			 put("Field_190","");
			 put("Field_191","");
			 put("Field_192","");
			 put("Field_193","");
			 put("Field_194","");
		}
		};*/
}
