package com.appstek.dc.dto;

public class TextFileDto {
	public String STATEPOSTALCODE;
	public String COUNTYNAME;
	public String APNORPINNUMBER;
	public String DUPLICATEAPNMULTIADDRESSID;
	public String PROPADDRSRCEFLAG;
	public String PROPHOUSENUMBER;
	public String PROPHOUSEALPHA;
	public String PROPSTREETDIRECTIONLEFT;
	public String PROPSTREETNAME;
	public String PROPSTREETSUFFIX;
	public String PROPSTREETDIRECTIONRIGHT;
	public String PROPUNITNUMBER;
	public String PROPFULLSTREETADDRESS;
	public String PROPCITYNAME;
	public String PROPSTATE;
	public String PROPZIPCODE;
	public String PROPZIP4;
	public String ASSESSEEOWNERNAME;
	public String SECOND_ASSESSEEOWNERNAME;
	public String ASSEVESTINGIDCODE;
	public String TAXACCOUNTNUMBER;
	public String ASSEMAILCAREOFNAME;
	public String ASSEMAILHOUSENUMBER;
	public String ASSEMAILHOUSEALPHA;
	public String ASSEMAILSTREETDIRECTIONLEFT;
	public String ASSEMAILSTREETNAME;
	public String ASSEMAILSTREETSUFFIX;
	public String ASSEMAILSTREETDIRECTIONRIGHT;
	public String ASSEMAILUNITNUMBER;
	public String ASSEMAILFULLSTREETADDRESS;
	public String ASSEMAILCITYNAME;
	public String ASSEMAILSTATE;
	public String ASSEMAILZIPCODE;
	public String ASSEMAILZIP4;
	public String STATELANDUSECODE;
	public String OWNEROCCUPIEDSFRCONDO;
	public String ASSESSEDLANDVALUE;
	public String ASSESSEDIMPROVEMENTVALUE;
	public String TOTALASSESSEDVALUE;
	public String ASSESSMENTYEAR;
	public String CALIFHOMEOWNERSEXEMPTION;
	public String TAXEXEMPTIONCODE;
	public String TAXRATECODEAREA;
	public String TAXAMOUNT;
	public String TAXYEAR;
	public String TAXDELINQUENTYEAR;
	public String RECORDERSDOCUMENTNUMBER;
	public String RECORDERSBOOKNUMBER;
	public String RECORDERSPAGENUMBER;
	public String RECORDINGDATE;
	public String DOCUMENTTYPECOUNTYDESCRIPTION;
	public String SALESPRICE;
	public String SALESPRICECODE;
	public String PRIORSALEDATE;
	public String PRIORSALESPRICE;
	/*public String PRIORSALESCODE;
	public String LEGALLOTCODE;
	public String LEGALLOTNUMBER;
	public String LEGALLANDLOT;
	public String LEGALBLOCK;
	public String LEGALSECTION;
	public String LEGALDISTRICT;
	public String LEGALUNIT;
	public String LEGALCITYMUNICIPALITYTOWNSHIP;
	public String LEGALSUBDIVISIONNAME;
	public String LEGALPHASENO;
	public String LEGALTRACTNO;
	public String LEGALSECTWPRNGMER;
	public String LEGALBRIEFDESCRIPTION;
	public String LEGALASSESSORSMAPREF;
	public String COUNTYLANDUSEDESCRIPTION;
	public String COUNTYLANDUSECODE;
	public String STANDARDIZEDLANDUSECODE;
	public String TIMESHARECODE;
	public String ZONING;
	public String LOTSIZEORAREA;
	public String BUILDINGAREA;
	public String YEARBUILT;
	public String NOOFBUILDINGS;
	public String NOOFSTORIES;
	public String NOOFUNITS;
	public String TOTALNOOFROOMS;
	public String NOOFBEDROOMS;
	public String NOOFBATHS;
	public String NOOFPARTIALBATHS;
	public String GARAGETYPEPARKING;
	public String PARKINGNUMBEROFCARS;
	public String POOL;
	public String MAILCITYSTZIP;
	public String FIPSCODE;
	public String TAPECUTDATE;
	public String CENSUSTRACT;
	public String RECORDTYPE;
	public String MARKETVALUELAND;
	public String MARKETVALUEIMPROVEMENT;
	public String TOTALMARKETVALUE;
	public String MARKETVALUEYEAR;
	public String BUILDINGCLASS;
	public String STYLE;
	public String TYPECONSTRUCTION;
	public String EXTERIORWALLS;
	public String FOUNDATION;
	public String ROOFCOVER;
	public String HEATING;
	public String AIRCONDITIONING;
	public String ELEVATOR;
	public String FIREPLACE;
	public String BASEMENT;
	public String EDITIONNUMBER;
	public String PROPERTYCOUNTRYCODE;
	public String BUILDINGAREAINDICATOR;
	public String PROPADDRMATCHCODE;
	public String PROPADDRUNITDESIGNATOR;
	public String PROPADDRUNITNUMBER;
	public String PROPADDRCARRIERROUTE;
	public String PROPADDRGEOCODEMATCHCODE;
	public String PROPADDRLATITUDE;
	public String PROPADDRLONGITUDE;
	public String PROPADDRCENSUSTRACTBLOCK;
	public String MAILADDRMATCHCODE;
	public String MAILADDRUNITDESIGNATOR;
	public String MAILADDRUNITNUMBER;
	public String MAILADDRCARRIERROUTE;
	public String ASSESSEEOWNERNAMEINDICATOR;
	public String SECOND_ASSESSEEOWNER_INDICATOR;
	public String MAILCAREOFNAMEINDICATOR;
	public String ASSESSEEOWNERNAMETYPE;
	public String SECONDASSESSEEOWNERNAMETYPE;
	public String ALTOLDAPNINDICATOR;
	public String CERTIFICATIONDATE;
	public String LOTSIZESQFT;
	public String BUILDINGQUALITY;
	public String FLOORCOVER;
	public String NOOFPLUMBINGFIXTURES;
	public String BUILDINGAREA1;
	public String BUILDINGAREA1INDICATOR;
	public String BUILDINGAREA2;
	public String BUILDINGAREA2INDICATOR;
	public String BUILDINGAREA3;
	public String BUILDINGAREA3INDICATOR;
	public String BUILDINGAREA4;
	public String BUILDINGAREA4INDICATOR;
	public String BUILDINGAREA5;
	public String BUILDINGAREA5INDICATOR;
	public String BUILDINGAREA6;
	public String BUILDINGAREA6INDICATOR;
	public String BUILDINGAREA7;
	public String BUILDINGAREA7INDICATOR;
	public String EFFECTIVEYEARBUILT;
	public String HEATINGFUELTYPE;
	public String AIRCONDITIONINGTYPE;
	public String LOTSIZEACRES;
	public String MORTGAGELENDERNAME;
	public String INTERIORWALLS;
	public String SCHOOLTAXDISTRICT1;
	public String SCHOOLTAXDISTRICT1INDICATOR;
	public String SCHOOLTAXDISTRICT2;
	public String SCHOOLTAXDISTRICT2INDICATOR;
	public String SCHOOLTAXDISTRICT3;
	public String SCHOOLTAXDISTRICT3INDICATOR;
	public String SITEINFLUENCE;
	public String AMENITIES;
	public String OTHERIMPRBUILDINGINDICATOR1;
	public String OTHERIMPRBUILDINGINDICATOR2;
	public String OTHERIMPRBUILDINGINDICATOR3;
	public String OTHERIMPRBUILDINGINDICATOR4;
	public String NEIGHBORHOODCODE;
	public String CONDOPROJECTBUILDINGNAME;
	public String OTHERIMPRBUILDINGINDICATOR5;
	public String AMENITIES2;
	public String OTHERIMPRBUILDINGAREA1;
	public String OTHERIMPRBUILDINGAREA2;
	public String OTHERIMPRBUILDINGAREA3;
	public String OTHERIMPRBUILDINGAREA4;
	public String OTHERIMPRBUILDINGAREA5;
	public String OTHERROOMS;
	public String EXTRAFEATURES1AREA;
	public String EXTRAFEATURES1INDICATOR;
	public String TOPOGRAPHY;
	public String ROOFTYPE;
	public String EXTRAFEATURES2AREA;
	public String EXTRAFEATURES2INDICATOR;
	public String EXTRAFEATURES3AREA;
	public String EXTRAFEATURES3INDICATOR;
	public String EXTRAFEATURES4AREA;
	public String EXTRAFEATURES4INDICATOR;
	public String OLDAPN;
	public String BUILDINGCONDITION;
	public String LOTSIZEFRONTAGEFEET;
	public String LOTSIZEDEPTHFEET;
	public String COMMENTS;
	public String WATER;
	public String SEWER;
	public String NEWRECORDTYPE;*/
	public String getSTATEPOSTALCODE() {
		return STATEPOSTALCODE;
	}
	public void setSTATEPOSTALCODE(String sTATEPOSTALCODE) {
		STATEPOSTALCODE = sTATEPOSTALCODE;
	}
	public String getCOUNTYNAME() {
		return COUNTYNAME;
	}
	public void setCOUNTYNAME(String cOUNTYNAME) {
		COUNTYNAME = cOUNTYNAME;
	}
	public String getAPNORPINNUMBER() {
		return APNORPINNUMBER;
	}
	public void setAPNORPINNUMBER(String aPNORPINNUMBER) {
		APNORPINNUMBER = aPNORPINNUMBER;
	}
	public String getDUPLICATEAPNMULTIADDRESSID() {
		return DUPLICATEAPNMULTIADDRESSID;
	}
	public void setDUPLICATEAPNMULTIADDRESSID(String dUPLICATEAPNMULTIADDRESSID) {
		DUPLICATEAPNMULTIADDRESSID = dUPLICATEAPNMULTIADDRESSID;
	}
	public String getPROPADDRSRCEFLAG() {
		return PROPADDRSRCEFLAG;
	}
	public void setPROPADDRSRCEFLAG(String pROPADDRSRCEFLAG) {
		PROPADDRSRCEFLAG = pROPADDRSRCEFLAG;
	}
	public String getPROPHOUSENUMBER() {
		return PROPHOUSENUMBER;
	}
	public void setPROPHOUSENUMBER(String pROPHOUSENUMBER) {
		PROPHOUSENUMBER = pROPHOUSENUMBER;
	}
	public String getPROPHOUSEALPHA() {
		return PROPHOUSEALPHA;
	}
	public void setPROPHOUSEALPHA(String pROPHOUSEALPHA) {
		PROPHOUSEALPHA = pROPHOUSEALPHA;
	}
	public String getPROPSTREETDIRECTIONLEFT() {
		return PROPSTREETDIRECTIONLEFT;
	}
	public void setPROPSTREETDIRECTIONLEFT(String pROPSTREETDIRECTIONLEFT) {
		PROPSTREETDIRECTIONLEFT = pROPSTREETDIRECTIONLEFT;
	}
	public String getPROPSTREETNAME() {
		return PROPSTREETNAME;
	}
	public void setPROPSTREETNAME(String pROPSTREETNAME) {
		PROPSTREETNAME = pROPSTREETNAME;
	}
	public String getPROPSTREETSUFFIX() {
		return PROPSTREETSUFFIX;
	}
	public void setPROPSTREETSUFFIX(String pROPSTREETSUFFIX) {
		PROPSTREETSUFFIX = pROPSTREETSUFFIX;
	}
	public String getPROPSTREETDIRECTIONRIGHT() {
		return PROPSTREETDIRECTIONRIGHT;
	}
	public void setPROPSTREETDIRECTIONRIGHT(String pROPSTREETDIRECTIONRIGHT) {
		PROPSTREETDIRECTIONRIGHT = pROPSTREETDIRECTIONRIGHT;
	}
	public String getPROPUNITNUMBER() {
		return PROPUNITNUMBER;
	}
	public void setPROPUNITNUMBER(String pROPUNITNUMBER) {
		PROPUNITNUMBER = pROPUNITNUMBER;
	}
	public String getPROPFULLSTREETADDRESS() {
		return PROPFULLSTREETADDRESS;
	}
	public void setPROPFULLSTREETADDRESS(String pROPFULLSTREETADDRESS) {
		PROPFULLSTREETADDRESS = pROPFULLSTREETADDRESS;
	}
	public String getPROPCITYNAME() {
		return PROPCITYNAME;
	}
	public void setPROPCITYNAME(String pROPCITYNAME) {
		PROPCITYNAME = pROPCITYNAME;
	}
	public String getPROPSTATE() {
		return PROPSTATE;
	}
	public void setPROPSTATE(String pROPSTATE) {
		PROPSTATE = pROPSTATE;
	}
	public String getPROPZIPCODE() {
		return PROPZIPCODE;
	}
	public void setPROPZIPCODE(String pROPZIPCODE) {
		PROPZIPCODE = pROPZIPCODE;
	}
	public String getPROPZIP4() {
		return PROPZIP4;
	}
	public void setPROPZIP4(String pROPZIP4) {
		PROPZIP4 = pROPZIP4;
	}
	public String getASSESSEEOWNERNAME() {
		return ASSESSEEOWNERNAME;
	}
	public void setASSESSEEOWNERNAME(String aSSESSEEOWNERNAME) {
		ASSESSEEOWNERNAME = aSSESSEEOWNERNAME;
	}
	public String getSECOND_ASSESSEEOWNERNAME() {
		return SECOND_ASSESSEEOWNERNAME;
	}
	public void setSECOND_ASSESSEEOWNERNAME(String sECOND_ASSESSEEOWNERNAME) {
		SECOND_ASSESSEEOWNERNAME = sECOND_ASSESSEEOWNERNAME;
	}
	public String getASSEVESTINGIDCODE() {
		return ASSEVESTINGIDCODE;
	}
	public void setASSEVESTINGIDCODE(String aSSEVESTINGIDCODE) {
		ASSEVESTINGIDCODE = aSSEVESTINGIDCODE;
	}
	public String getTAXACCOUNTNUMBER() {
		return TAXACCOUNTNUMBER;
	}
	public void setTAXACCOUNTNUMBER(String tAXACCOUNTNUMBER) {
		TAXACCOUNTNUMBER = tAXACCOUNTNUMBER;
	}
	public String getASSEMAILCAREOFNAME() {
		return ASSEMAILCAREOFNAME;
	}
	public void setASSEMAILCAREOFNAME(String aSSEMAILCAREOFNAME) {
		ASSEMAILCAREOFNAME = aSSEMAILCAREOFNAME;
	}
	public String getASSEMAILHOUSENUMBER() {
		return ASSEMAILHOUSENUMBER;
	}
	public void setASSEMAILHOUSENUMBER(String aSSEMAILHOUSENUMBER) {
		ASSEMAILHOUSENUMBER = aSSEMAILHOUSENUMBER;
	}
	public String getASSEMAILHOUSEALPHA() {
		return ASSEMAILHOUSEALPHA;
	}
	public void setASSEMAILHOUSEALPHA(String aSSEMAILHOUSEALPHA) {
		ASSEMAILHOUSEALPHA = aSSEMAILHOUSEALPHA;
	}
	public String getASSEMAILSTREETDIRECTIONLEFT() {
		return ASSEMAILSTREETDIRECTIONLEFT;
	}
	public void setASSEMAILSTREETDIRECTIONLEFT(String aSSEMAILSTREETDIRECTIONLEFT) {
		ASSEMAILSTREETDIRECTIONLEFT = aSSEMAILSTREETDIRECTIONLEFT;
	}
	public String getASSEMAILSTREETNAME() {
		return ASSEMAILSTREETNAME;
	}
	public void setASSEMAILSTREETNAME(String aSSEMAILSTREETNAME) {
		ASSEMAILSTREETNAME = aSSEMAILSTREETNAME;
	}
	public String getASSEMAILSTREETSUFFIX() {
		return ASSEMAILSTREETSUFFIX;
	}
	public void setASSEMAILSTREETSUFFIX(String aSSEMAILSTREETSUFFIX) {
		ASSEMAILSTREETSUFFIX = aSSEMAILSTREETSUFFIX;
	}
	public String getASSEMAILSTREETDIRECTIONRIGHT() {
		return ASSEMAILSTREETDIRECTIONRIGHT;
	}
	public void setASSEMAILSTREETDIRECTIONRIGHT(String aSSEMAILSTREETDIRECTIONRIGHT) {
		ASSEMAILSTREETDIRECTIONRIGHT = aSSEMAILSTREETDIRECTIONRIGHT;
	}
	public String getASSEMAILUNITNUMBER() {
		return ASSEMAILUNITNUMBER;
	}
	public void setASSEMAILUNITNUMBER(String aSSEMAILUNITNUMBER) {
		ASSEMAILUNITNUMBER = aSSEMAILUNITNUMBER;
	}
	public String getASSEMAILFULLSTREETADDRESS() {
		return ASSEMAILFULLSTREETADDRESS;
	}
	public void setASSEMAILFULLSTREETADDRESS(String aSSEMAILFULLSTREETADDRESS) {
		ASSEMAILFULLSTREETADDRESS = aSSEMAILFULLSTREETADDRESS;
	}
	public String getASSEMAILCITYNAME() {
		return ASSEMAILCITYNAME;
	}
	public void setASSEMAILCITYNAME(String aSSEMAILCITYNAME) {
		ASSEMAILCITYNAME = aSSEMAILCITYNAME;
	}
	public String getASSEMAILSTATE() {
		return ASSEMAILSTATE;
	}
	public void setASSEMAILSTATE(String aSSEMAILSTATE) {
		ASSEMAILSTATE = aSSEMAILSTATE;
	}
	public String getASSEMAILZIPCODE() {
		return ASSEMAILZIPCODE;
	}
	public void setASSEMAILZIPCODE(String aSSEMAILZIPCODE) {
		ASSEMAILZIPCODE = aSSEMAILZIPCODE;
	}
	public String getASSEMAILZIP4() {
		return ASSEMAILZIP4;
	}
	public void setASSEMAILZIP4(String aSSEMAILZIP4) {
		ASSEMAILZIP4 = aSSEMAILZIP4;
	}
	public String getSTATELANDUSECODE() {
		return STATELANDUSECODE;
	}
	public void setSTATELANDUSECODE(String sTATELANDUSECODE) {
		STATELANDUSECODE = sTATELANDUSECODE;
	}
	public String getOWNEROCCUPIEDSFRCONDO() {
		return OWNEROCCUPIEDSFRCONDO;
	}
	public void setOWNEROCCUPIEDSFRCONDO(String oWNEROCCUPIEDSFRCONDO) {
		OWNEROCCUPIEDSFRCONDO = oWNEROCCUPIEDSFRCONDO;
	}
	public String getASSESSEDLANDVALUE() {
		return ASSESSEDLANDVALUE;
	}
	public void setASSESSEDLANDVALUE(String aSSESSEDLANDVALUE) {
		ASSESSEDLANDVALUE = aSSESSEDLANDVALUE;
	}
	public String getASSESSEDIMPROVEMENTVALUE() {
		return ASSESSEDIMPROVEMENTVALUE;
	}
	public void setASSESSEDIMPROVEMENTVALUE(String aSSESSEDIMPROVEMENTVALUE) {
		ASSESSEDIMPROVEMENTVALUE = aSSESSEDIMPROVEMENTVALUE;
	}
	public String getTOTALASSESSEDVALUE() {
		return TOTALASSESSEDVALUE;
	}
	public void setTOTALASSESSEDVALUE(String tOTALASSESSEDVALUE) {
		TOTALASSESSEDVALUE = tOTALASSESSEDVALUE;
	}
	public String getASSESSMENTYEAR() {
		return ASSESSMENTYEAR;
	}
	public void setASSESSMENTYEAR(String aSSESSMENTYEAR) {
		ASSESSMENTYEAR = aSSESSMENTYEAR;
	}
	public String getCALIFHOMEOWNERSEXEMPTION() {
		return CALIFHOMEOWNERSEXEMPTION;
	}
	public void setCALIFHOMEOWNERSEXEMPTION(String cALIFHOMEOWNERSEXEMPTION) {
		CALIFHOMEOWNERSEXEMPTION = cALIFHOMEOWNERSEXEMPTION;
	}
	public String getTAXEXEMPTIONCODE() {
		return TAXEXEMPTIONCODE;
	}
	public void setTAXEXEMPTIONCODE(String tAXEXEMPTIONCODE) {
		TAXEXEMPTIONCODE = tAXEXEMPTIONCODE;
	}
	public String getTAXRATECODEAREA() {
		return TAXRATECODEAREA;
	}
	public void setTAXRATECODEAREA(String tAXRATECODEAREA) {
		TAXRATECODEAREA = tAXRATECODEAREA;
	}
	public String getTAXAMOUNT() {
		return TAXAMOUNT;
	}
	public void setTAXAMOUNT(String tAXAMOUNT) {
		TAXAMOUNT = tAXAMOUNT;
	}
	public String getTAXYEAR() {
		return TAXYEAR;
	}
	public void setTAXYEAR(String tAXYEAR) {
		TAXYEAR = tAXYEAR;
	}
	public String getTAXDELINQUENTYEAR() {
		return TAXDELINQUENTYEAR;
	}
	public void setTAXDELINQUENTYEAR(String tAXDELINQUENTYEAR) {
		TAXDELINQUENTYEAR = tAXDELINQUENTYEAR;
	}
	public String getRECORDERSDOCUMENTNUMBER() {
		return RECORDERSDOCUMENTNUMBER;
	}
	public void setRECORDERSDOCUMENTNUMBER(String rECORDERSDOCUMENTNUMBER) {
		RECORDERSDOCUMENTNUMBER = rECORDERSDOCUMENTNUMBER;
	}
	public String getRECORDERSBOOKNUMBER() {
		return RECORDERSBOOKNUMBER;
	}
	public void setRECORDERSBOOKNUMBER(String rECORDERSBOOKNUMBER) {
		RECORDERSBOOKNUMBER = rECORDERSBOOKNUMBER;
	}
	public String getRECORDERSPAGENUMBER() {
		return RECORDERSPAGENUMBER;
	}
	public void setRECORDERSPAGENUMBER(String rECORDERSPAGENUMBER) {
		RECORDERSPAGENUMBER = rECORDERSPAGENUMBER;
	}
	public String getRECORDINGDATE() {
		return RECORDINGDATE;
	}
	public void setRECORDINGDATE(String rECORDINGDATE) {
		RECORDINGDATE = rECORDINGDATE;
	}
	public String getDOCUMENTTYPECOUNTYDESCRIPTION() {
		return DOCUMENTTYPECOUNTYDESCRIPTION;
	}
	public void setDOCUMENTTYPECOUNTYDESCRIPTION(String dOCUMENTTYPECOUNTYDESCRIPTION) {
		DOCUMENTTYPECOUNTYDESCRIPTION = dOCUMENTTYPECOUNTYDESCRIPTION;
	}
	public String getSALESPRICE() {
		return SALESPRICE;
	}
	public void setSALESPRICE(String sALESPRICE) {
		SALESPRICE = sALESPRICE;
	}
	public String getSALESPRICECODE() {
		return SALESPRICECODE;
	}
	public void setSALESPRICECODE(String sALESPRICECODE) {
		SALESPRICECODE = sALESPRICECODE;
	}
	public String getPRIORSALEDATE() {
		return PRIORSALEDATE;
	}
	public void setPRIORSALEDATE(String pRIORSALEDATE) {
		PRIORSALEDATE = pRIORSALEDATE;
	}
	public String getPRIORSALESPRICE() {
		return PRIORSALESPRICE;
	}
	public void setPRIORSALESPRICE(String pRIORSALESPRICE) {
		PRIORSALESPRICE = pRIORSALESPRICE;
	}
	/*public String getPRIORSALESCODE() {
		return PRIORSALESCODE;
	}
	public void setPRIORSALESCODE(String pRIORSALESCODE) {
		PRIORSALESCODE = pRIORSALESCODE;
	}
	public String getLEGALLOTCODE() {
		return LEGALLOTCODE;
	}
	public void setLEGALLOTCODE(String lEGALLOTCODE) {
		LEGALLOTCODE = lEGALLOTCODE;
	}
	public String getLEGALLOTNUMBER() {
		return LEGALLOTNUMBER;
	}
	public void setLEGALLOTNUMBER(String lEGALLOTNUMBER) {
		LEGALLOTNUMBER = lEGALLOTNUMBER;
	}
	public String getLEGALLANDLOT() {
		return LEGALLANDLOT;
	}
	public void setLEGALLANDLOT(String lEGALLANDLOT) {
		LEGALLANDLOT = lEGALLANDLOT;
	}
	public String getLEGALBLOCK() {
		return LEGALBLOCK;
	}
	public void setLEGALBLOCK(String lEGALBLOCK) {
		LEGALBLOCK = lEGALBLOCK;
	}
	public String getLEGALSECTION() {
		return LEGALSECTION;
	}
	public void setLEGALSECTION(String lEGALSECTION) {
		LEGALSECTION = lEGALSECTION;
	}
	public String getLEGALDISTRICT() {
		return LEGALDISTRICT;
	}
	public void setLEGALDISTRICT(String lEGALDISTRICT) {
		LEGALDISTRICT = lEGALDISTRICT;
	}
	public String getLEGALUNIT() {
		return LEGALUNIT;
	}
	public void setLEGALUNIT(String lEGALUNIT) {
		LEGALUNIT = lEGALUNIT;
	}
	public String getLEGALCITYMUNICIPALITYTOWNSHIP() {
		return LEGALCITYMUNICIPALITYTOWNSHIP;
	}
	public void setLEGALCITYMUNICIPALITYTOWNSHIP(String lEGALCITYMUNICIPALITYTOWNSHIP) {
		LEGALCITYMUNICIPALITYTOWNSHIP = lEGALCITYMUNICIPALITYTOWNSHIP;
	}
	public String getLEGALSUBDIVISIONNAME() {
		return LEGALSUBDIVISIONNAME;
	}
	public void setLEGALSUBDIVISIONNAME(String lEGALSUBDIVISIONNAME) {
		LEGALSUBDIVISIONNAME = lEGALSUBDIVISIONNAME;
	}
	public String getLEGALPHASENO() {
		return LEGALPHASENO;
	}
	public void setLEGALPHASENO(String lEGALPHASENO) {
		LEGALPHASENO = lEGALPHASENO;
	}
	public String getLEGALTRACTNO() {
		return LEGALTRACTNO;
	}
	public void setLEGALTRACTNO(String lEGALTRACTNO) {
		LEGALTRACTNO = lEGALTRACTNO;
	}
	public String getLEGALSECTWPRNGMER() {
		return LEGALSECTWPRNGMER;
	}
	public void setLEGALSECTWPRNGMER(String lEGALSECTWPRNGMER) {
		LEGALSECTWPRNGMER = lEGALSECTWPRNGMER;
	}
	public String getLEGALBRIEFDESCRIPTION() {
		return LEGALBRIEFDESCRIPTION;
	}
	public void setLEGALBRIEFDESCRIPTION(String lEGALBRIEFDESCRIPTION) {
		LEGALBRIEFDESCRIPTION = lEGALBRIEFDESCRIPTION;
	}
	public String getLEGALASSESSORSMAPREF() {
		return LEGALASSESSORSMAPREF;
	}
	public void setLEGALASSESSORSMAPREF(String lEGALASSESSORSMAPREF) {
		LEGALASSESSORSMAPREF = lEGALASSESSORSMAPREF;
	}
	public String getCOUNTYLANDUSEDESCRIPTION() {
		return COUNTYLANDUSEDESCRIPTION;
	}
	public void setCOUNTYLANDUSEDESCRIPTION(String cOUNTYLANDUSEDESCRIPTION) {
		COUNTYLANDUSEDESCRIPTION = cOUNTYLANDUSEDESCRIPTION;
	}
	public String getCOUNTYLANDUSECODE() {
		return COUNTYLANDUSECODE;
	}
	public void setCOUNTYLANDUSECODE(String cOUNTYLANDUSECODE) {
		COUNTYLANDUSECODE = cOUNTYLANDUSECODE;
	}
	public String getSTANDARDIZEDLANDUSECODE() {
		return STANDARDIZEDLANDUSECODE;
	}
	public void setSTANDARDIZEDLANDUSECODE(String sTANDARDIZEDLANDUSECODE) {
		STANDARDIZEDLANDUSECODE = sTANDARDIZEDLANDUSECODE;
	}
	public String getTIMESHARECODE() {
		return TIMESHARECODE;
	}
	public void setTIMESHARECODE(String tIMESHARECODE) {
		TIMESHARECODE = tIMESHARECODE;
	}
	public String getZONING() {
		return ZONING;
	}
	public void setZONING(String zONING) {
		ZONING = zONING;
	}
	public String getLOTSIZEORAREA() {
		return LOTSIZEORAREA;
	}
	public void setLOTSIZEORAREA(String lOTSIZEORAREA) {
		LOTSIZEORAREA = lOTSIZEORAREA;
	}
	public String getBUILDINGAREA() {
		return BUILDINGAREA;
	}
	public void setBUILDINGAREA(String bUILDINGAREA) {
		BUILDINGAREA = bUILDINGAREA;
	}
	public String getYEARBUILT() {
		return YEARBUILT;
	}
	public void setYEARBUILT(String yEARBUILT) {
		YEARBUILT = yEARBUILT;
	}
	public String getNOOFBUILDINGS() {
		return NOOFBUILDINGS;
	}
	public void setNOOFBUILDINGS(String nOOFBUILDINGS) {
		NOOFBUILDINGS = nOOFBUILDINGS;
	}
	public String getNOOFSTORIES() {
		return NOOFSTORIES;
	}
	public void setNOOFSTORIES(String nOOFSTORIES) {
		NOOFSTORIES = nOOFSTORIES;
	}
	public String getNOOFUNITS() {
		return NOOFUNITS;
	}
	public void setNOOFUNITS(String nOOFUNITS) {
		NOOFUNITS = nOOFUNITS;
	}
	public String getTOTALNOOFROOMS() {
		return TOTALNOOFROOMS;
	}
	public void setTOTALNOOFROOMS(String tOTALNOOFROOMS) {
		TOTALNOOFROOMS = tOTALNOOFROOMS;
	}
	public String getNOOFBEDROOMS() {
		return NOOFBEDROOMS;
	}
	public void setNOOFBEDROOMS(String nOOFBEDROOMS) {
		NOOFBEDROOMS = nOOFBEDROOMS;
	}
	public String getNOOFBATHS() {
		return NOOFBATHS;
	}
	public void setNOOFBATHS(String nOOFBATHS) {
		NOOFBATHS = nOOFBATHS;
	}
	public String getNOOFPARTIALBATHS() {
		return NOOFPARTIALBATHS;
	}
	public void setNOOFPARTIALBATHS(String nOOFPARTIALBATHS) {
		NOOFPARTIALBATHS = nOOFPARTIALBATHS;
	}
	public String getGARAGETYPEPARKING() {
		return GARAGETYPEPARKING;
	}
	public void setGARAGETYPEPARKING(String gARAGETYPEPARKING) {
		GARAGETYPEPARKING = gARAGETYPEPARKING;
	}
	public String getPARKINGNUMBEROFCARS() {
		return PARKINGNUMBEROFCARS;
	}
	public void setPARKINGNUMBEROFCARS(String pARKINGNUMBEROFCARS) {
		PARKINGNUMBEROFCARS = pARKINGNUMBEROFCARS;
	}
	public String getPOOL() {
		return POOL;
	}
	public void setPOOL(String pOOL) {
		POOL = pOOL;
	}
	public String getMAILCITYSTZIP() {
		return MAILCITYSTZIP;
	}
	public void setMAILCITYSTZIP(String mAILCITYSTZIP) {
		MAILCITYSTZIP = mAILCITYSTZIP;
	}
	public String getFIPSCODE() {
		return FIPSCODE;
	}
	public void setFIPSCODE(String fIPSCODE) {
		FIPSCODE = fIPSCODE;
	}
	public String getTAPECUTDATE() {
		return TAPECUTDATE;
	}
	public void setTAPECUTDATE(String tAPECUTDATE) {
		TAPECUTDATE = tAPECUTDATE;
	}
	public String getCENSUSTRACT() {
		return CENSUSTRACT;
	}
	public void setCENSUSTRACT(String cENSUSTRACT) {
		CENSUSTRACT = cENSUSTRACT;
	}
	public String getRECORDTYPE() {
		return RECORDTYPE;
	}
	public void setRECORDTYPE(String rECORDTYPE) {
		RECORDTYPE = rECORDTYPE;
	}
	public String getMARKETVALUELAND() {
		return MARKETVALUELAND;
	}
	public void setMARKETVALUELAND(String mARKETVALUELAND) {
		MARKETVALUELAND = mARKETVALUELAND;
	}
	public String getMARKETVALUEIMPROVEMENT() {
		return MARKETVALUEIMPROVEMENT;
	}
	public void setMARKETVALUEIMPROVEMENT(String mARKETVALUEIMPROVEMENT) {
		MARKETVALUEIMPROVEMENT = mARKETVALUEIMPROVEMENT;
	}
	public String getTOTALMARKETVALUE() {
		return TOTALMARKETVALUE;
	}
	public void setTOTALMARKETVALUE(String tOTALMARKETVALUE) {
		TOTALMARKETVALUE = tOTALMARKETVALUE;
	}
	public String getMARKETVALUEYEAR() {
		return MARKETVALUEYEAR;
	}
	public void setMARKETVALUEYEAR(String mARKETVALUEYEAR) {
		MARKETVALUEYEAR = mARKETVALUEYEAR;
	}
	public String getBUILDINGCLASS() {
		return BUILDINGCLASS;
	}
	public void setBUILDINGCLASS(String bUILDINGCLASS) {
		BUILDINGCLASS = bUILDINGCLASS;
	}
	public String getSTYLE() {
		return STYLE;
	}
	public void setSTYLE(String sTYLE) {
		STYLE = sTYLE;
	}
	public String getTYPECONSTRUCTION() {
		return TYPECONSTRUCTION;
	}
	public void setTYPECONSTRUCTION(String tYPECONSTRUCTION) {
		TYPECONSTRUCTION = tYPECONSTRUCTION;
	}
	public String getEXTERIORWALLS() {
		return EXTERIORWALLS;
	}
	public void setEXTERIORWALLS(String eXTERIORWALLS) {
		EXTERIORWALLS = eXTERIORWALLS;
	}
	public String getFOUNDATION() {
		return FOUNDATION;
	}
	public void setFOUNDATION(String fOUNDATION) {
		FOUNDATION = fOUNDATION;
	}
	public String getROOFCOVER() {
		return ROOFCOVER;
	}
	public void setROOFCOVER(String rOOFCOVER) {
		ROOFCOVER = rOOFCOVER;
	}
	public String getHEATING() {
		return HEATING;
	}
	public void setHEATING(String hEATING) {
		HEATING = hEATING;
	}
	public String getAIRCONDITIONING() {
		return AIRCONDITIONING;
	}
	public void setAIRCONDITIONING(String aIRCONDITIONING) {
		AIRCONDITIONING = aIRCONDITIONING;
	}
	public String getELEVATOR() {
		return ELEVATOR;
	}
	public void setELEVATOR(String eLEVATOR) {
		ELEVATOR = eLEVATOR;
	}
	public String getFIREPLACE() {
		return FIREPLACE;
	}
	public void setFIREPLACE(String fIREPLACE) {
		FIREPLACE = fIREPLACE;
	}
	public String getBASEMENT() {
		return BASEMENT;
	}
	public void setBASEMENT(String bASEMENT) {
		BASEMENT = bASEMENT;
	}
	public String getEDITIONNUMBER() {
		return EDITIONNUMBER;
	}
	public void setEDITIONNUMBER(String eDITIONNUMBER) {
		EDITIONNUMBER = eDITIONNUMBER;
	}
	public String getPROPERTYCOUNTRYCODE() {
		return PROPERTYCOUNTRYCODE;
	}
	public void setPROPERTYCOUNTRYCODE(String pROPERTYCOUNTRYCODE) {
		PROPERTYCOUNTRYCODE = pROPERTYCOUNTRYCODE;
	}
	public String getBUILDINGAREAINDICATOR() {
		return BUILDINGAREAINDICATOR;
	}
	public void setBUILDINGAREAINDICATOR(String bUILDINGAREAINDICATOR) {
		BUILDINGAREAINDICATOR = bUILDINGAREAINDICATOR;
	}
	public String getPROPADDRMATCHCODE() {
		return PROPADDRMATCHCODE;
	}
	public void setPROPADDRMATCHCODE(String pROPADDRMATCHCODE) {
		PROPADDRMATCHCODE = pROPADDRMATCHCODE;
	}
	public String getPROPADDRUNITDESIGNATOR() {
		return PROPADDRUNITDESIGNATOR;
	}
	public void setPROPADDRUNITDESIGNATOR(String pROPADDRUNITDESIGNATOR) {
		PROPADDRUNITDESIGNATOR = pROPADDRUNITDESIGNATOR;
	}
	public String getPROPADDRUNITNUMBER() {
		return PROPADDRUNITNUMBER;
	}
	public void setPROPADDRUNITNUMBER(String pROPADDRUNITNUMBER) {
		PROPADDRUNITNUMBER = pROPADDRUNITNUMBER;
	}
	public String getPROPADDRCARRIERROUTE() {
		return PROPADDRCARRIERROUTE;
	}
	public void setPROPADDRCARRIERROUTE(String pROPADDRCARRIERROUTE) {
		PROPADDRCARRIERROUTE = pROPADDRCARRIERROUTE;
	}
	public String getPROPADDRGEOCODEMATCHCODE() {
		return PROPADDRGEOCODEMATCHCODE;
	}
	public void setPROPADDRGEOCODEMATCHCODE(String pROPADDRGEOCODEMATCHCODE) {
		PROPADDRGEOCODEMATCHCODE = pROPADDRGEOCODEMATCHCODE;
	}
	public String getPROPADDRLATITUDE() {
		return PROPADDRLATITUDE;
	}
	public void setPROPADDRLATITUDE(String pROPADDRLATITUDE) {
		PROPADDRLATITUDE = pROPADDRLATITUDE;
	}
	public String getPROPADDRLONGITUDE() {
		return PROPADDRLONGITUDE;
	}
	public void setPROPADDRLONGITUDE(String pROPADDRLONGITUDE) {
		PROPADDRLONGITUDE = pROPADDRLONGITUDE;
	}
	public String getPROPADDRCENSUSTRACTBLOCK() {
		return PROPADDRCENSUSTRACTBLOCK;
	}
	public void setPROPADDRCENSUSTRACTBLOCK(String pROPADDRCENSUSTRACTBLOCK) {
		PROPADDRCENSUSTRACTBLOCK = pROPADDRCENSUSTRACTBLOCK;
	}
	public String getMAILADDRMATCHCODE() {
		return MAILADDRMATCHCODE;
	}
	public void setMAILADDRMATCHCODE(String mAILADDRMATCHCODE) {
		MAILADDRMATCHCODE = mAILADDRMATCHCODE;
	}
	public String getMAILADDRUNITDESIGNATOR() {
		return MAILADDRUNITDESIGNATOR;
	}
	public void setMAILADDRUNITDESIGNATOR(String mAILADDRUNITDESIGNATOR) {
		MAILADDRUNITDESIGNATOR = mAILADDRUNITDESIGNATOR;
	}
	public String getMAILADDRUNITNUMBER() {
		return MAILADDRUNITNUMBER;
	}
	public void setMAILADDRUNITNUMBER(String mAILADDRUNITNUMBER) {
		MAILADDRUNITNUMBER = mAILADDRUNITNUMBER;
	}
	public String getMAILADDRCARRIERROUTE() {
		return MAILADDRCARRIERROUTE;
	}
	public void setMAILADDRCARRIERROUTE(String mAILADDRCARRIERROUTE) {
		MAILADDRCARRIERROUTE = mAILADDRCARRIERROUTE;
	}
	public String getASSESSEEOWNERNAMEINDICATOR() {
		return ASSESSEEOWNERNAMEINDICATOR;
	}
	public void setASSESSEEOWNERNAMEINDICATOR(String aSSESSEEOWNERNAMEINDICATOR) {
		ASSESSEEOWNERNAMEINDICATOR = aSSESSEEOWNERNAMEINDICATOR;
	}
	public String getSECOND_ASSESSEEOWNER_INDICATOR() {
		return SECOND_ASSESSEEOWNER_INDICATOR;
	}
	public void setSECOND_ASSESSEEOWNER_INDICATOR(String sECOND_ASSESSEEOWNER_INDICATOR) {
		SECOND_ASSESSEEOWNER_INDICATOR = sECOND_ASSESSEEOWNER_INDICATOR;
	}
	public String getMAILCAREOFNAMEINDICATOR() {
		return MAILCAREOFNAMEINDICATOR;
	}
	public void setMAILCAREOFNAMEINDICATOR(String mAILCAREOFNAMEINDICATOR) {
		MAILCAREOFNAMEINDICATOR = mAILCAREOFNAMEINDICATOR;
	}
	public String getASSESSEEOWNERNAMETYPE() {
		return ASSESSEEOWNERNAMETYPE;
	}
	public void setASSESSEEOWNERNAMETYPE(String aSSESSEEOWNERNAMETYPE) {
		ASSESSEEOWNERNAMETYPE = aSSESSEEOWNERNAMETYPE;
	}
	public String getSECONDASSESSEEOWNERNAMETYPE() {
		return SECONDASSESSEEOWNERNAMETYPE;
	}
	public void setSECONDASSESSEEOWNERNAMETYPE(String sECONDASSESSEEOWNERNAMETYPE) {
		SECONDASSESSEEOWNERNAMETYPE = sECONDASSESSEEOWNERNAMETYPE;
	}
	public String getALTOLDAPNINDICATOR() {
		return ALTOLDAPNINDICATOR;
	}
	public void setALTOLDAPNINDICATOR(String aLTOLDAPNINDICATOR) {
		ALTOLDAPNINDICATOR = aLTOLDAPNINDICATOR;
	}
	public String getCERTIFICATIONDATE() {
		return CERTIFICATIONDATE;
	}
	public void setCERTIFICATIONDATE(String cERTIFICATIONDATE) {
		CERTIFICATIONDATE = cERTIFICATIONDATE;
	}
	public String getLOTSIZESQFT() {
		return LOTSIZESQFT;
	}
	public void setLOTSIZESQFT(String lOTSIZESQFT) {
		LOTSIZESQFT = lOTSIZESQFT;
	}
	public String getBUILDINGQUALITY() {
		return BUILDINGQUALITY;
	}
	public void setBUILDINGQUALITY(String bUILDINGQUALITY) {
		BUILDINGQUALITY = bUILDINGQUALITY;
	}
	public String getFLOORCOVER() {
		return FLOORCOVER;
	}
	public void setFLOORCOVER(String fLOORCOVER) {
		FLOORCOVER = fLOORCOVER;
	}
	public String getNOOFPLUMBINGFIXTURES() {
		return NOOFPLUMBINGFIXTURES;
	}
	public void setNOOFPLUMBINGFIXTURES(String nOOFPLUMBINGFIXTURES) {
		NOOFPLUMBINGFIXTURES = nOOFPLUMBINGFIXTURES;
	}
	public String getBUILDINGAREA1() {
		return BUILDINGAREA1;
	}
	public void setBUILDINGAREA1(String bUILDINGAREA1) {
		BUILDINGAREA1 = bUILDINGAREA1;
	}
	public String getBUILDINGAREA1INDICATOR() {
		return BUILDINGAREA1INDICATOR;
	}
	public void setBUILDINGAREA1INDICATOR(String bUILDINGAREA1INDICATOR) {
		BUILDINGAREA1INDICATOR = bUILDINGAREA1INDICATOR;
	}
	public String getBUILDINGAREA2() {
		return BUILDINGAREA2;
	}
	public void setBUILDINGAREA2(String bUILDINGAREA2) {
		BUILDINGAREA2 = bUILDINGAREA2;
	}
	public String getBUILDINGAREA2INDICATOR() {
		return BUILDINGAREA2INDICATOR;
	}
	public void setBUILDINGAREA2INDICATOR(String bUILDINGAREA2INDICATOR) {
		BUILDINGAREA2INDICATOR = bUILDINGAREA2INDICATOR;
	}
	public String getBUILDINGAREA3() {
		return BUILDINGAREA3;
	}
	public void setBUILDINGAREA3(String bUILDINGAREA3) {
		BUILDINGAREA3 = bUILDINGAREA3;
	}
	public String getBUILDINGAREA3INDICATOR() {
		return BUILDINGAREA3INDICATOR;
	}
	public void setBUILDINGAREA3INDICATOR(String bUILDINGAREA3INDICATOR) {
		BUILDINGAREA3INDICATOR = bUILDINGAREA3INDICATOR;
	}
	public String getBUILDINGAREA4() {
		return BUILDINGAREA4;
	}
	public void setBUILDINGAREA4(String bUILDINGAREA4) {
		BUILDINGAREA4 = bUILDINGAREA4;
	}
	public String getBUILDINGAREA4INDICATOR() {
		return BUILDINGAREA4INDICATOR;
	}
	public void setBUILDINGAREA4INDICATOR(String bUILDINGAREA4INDICATOR) {
		BUILDINGAREA4INDICATOR = bUILDINGAREA4INDICATOR;
	}
	public String getBUILDINGAREA5() {
		return BUILDINGAREA5;
	}
	public void setBUILDINGAREA5(String bUILDINGAREA5) {
		BUILDINGAREA5 = bUILDINGAREA5;
	}
	public String getBUILDINGAREA5INDICATOR() {
		return BUILDINGAREA5INDICATOR;
	}
	public void setBUILDINGAREA5INDICATOR(String bUILDINGAREA5INDICATOR) {
		BUILDINGAREA5INDICATOR = bUILDINGAREA5INDICATOR;
	}
	public String getBUILDINGAREA6() {
		return BUILDINGAREA6;
	}
	public void setBUILDINGAREA6(String bUILDINGAREA6) {
		BUILDINGAREA6 = bUILDINGAREA6;
	}
	public String getBUILDINGAREA6INDICATOR() {
		return BUILDINGAREA6INDICATOR;
	}
	public void setBUILDINGAREA6INDICATOR(String bUILDINGAREA6INDICATOR) {
		BUILDINGAREA6INDICATOR = bUILDINGAREA6INDICATOR;
	}
	public String getBUILDINGAREA7() {
		return BUILDINGAREA7;
	}
	public void setBUILDINGAREA7(String bUILDINGAREA7) {
		BUILDINGAREA7 = bUILDINGAREA7;
	}
	public String getBUILDINGAREA7INDICATOR() {
		return BUILDINGAREA7INDICATOR;
	}
	public void setBUILDINGAREA7INDICATOR(String bUILDINGAREA7INDICATOR) {
		BUILDINGAREA7INDICATOR = bUILDINGAREA7INDICATOR;
	}
	public String getEFFECTIVEYEARBUILT() {
		return EFFECTIVEYEARBUILT;
	}
	public void setEFFECTIVEYEARBUILT(String eFFECTIVEYEARBUILT) {
		EFFECTIVEYEARBUILT = eFFECTIVEYEARBUILT;
	}
	public String getHEATINGFUELTYPE() {
		return HEATINGFUELTYPE;
	}
	public void setHEATINGFUELTYPE(String hEATINGFUELTYPE) {
		HEATINGFUELTYPE = hEATINGFUELTYPE;
	}
	public String getAIRCONDITIONINGTYPE() {
		return AIRCONDITIONINGTYPE;
	}
	public void setAIRCONDITIONINGTYPE(String aIRCONDITIONINGTYPE) {
		AIRCONDITIONINGTYPE = aIRCONDITIONINGTYPE;
	}
	public String getLOTSIZEACRES() {
		return LOTSIZEACRES;
	}
	public void setLOTSIZEACRES(String lOTSIZEACRES) {
		LOTSIZEACRES = lOTSIZEACRES;
	}
	public String getMORTGAGELENDERNAME() {
		return MORTGAGELENDERNAME;
	}
	public void setMORTGAGELENDERNAME(String mORTGAGELENDERNAME) {
		MORTGAGELENDERNAME = mORTGAGELENDERNAME;
	}
	public String getINTERIORWALLS() {
		return INTERIORWALLS;
	}
	public void setINTERIORWALLS(String iNTERIORWALLS) {
		INTERIORWALLS = iNTERIORWALLS;
	}
	public String getSCHOOLTAXDISTRICT1() {
		return SCHOOLTAXDISTRICT1;
	}
	public void setSCHOOLTAXDISTRICT1(String sCHOOLTAXDISTRICT1) {
		SCHOOLTAXDISTRICT1 = sCHOOLTAXDISTRICT1;
	}
	public String getSCHOOLTAXDISTRICT1INDICATOR() {
		return SCHOOLTAXDISTRICT1INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT1INDICATOR(String sCHOOLTAXDISTRICT1INDICATOR) {
		SCHOOLTAXDISTRICT1INDICATOR = sCHOOLTAXDISTRICT1INDICATOR;
	}
	public String getSCHOOLTAXDISTRICT2() {
		return SCHOOLTAXDISTRICT2;
	}
	public void setSCHOOLTAXDISTRICT2(String sCHOOLTAXDISTRICT2) {
		SCHOOLTAXDISTRICT2 = sCHOOLTAXDISTRICT2;
	}
	public String getSCHOOLTAXDISTRICT2INDICATOR() {
		return SCHOOLTAXDISTRICT2INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT2INDICATOR(String sCHOOLTAXDISTRICT2INDICATOR) {
		SCHOOLTAXDISTRICT2INDICATOR = sCHOOLTAXDISTRICT2INDICATOR;
	}
	public String getSCHOOLTAXDISTRICT3() {
		return SCHOOLTAXDISTRICT3;
	}
	public void setSCHOOLTAXDISTRICT3(String sCHOOLTAXDISTRICT3) {
		SCHOOLTAXDISTRICT3 = sCHOOLTAXDISTRICT3;
	}
	public String getSCHOOLTAXDISTRICT3INDICATOR() {
		return SCHOOLTAXDISTRICT3INDICATOR;
	}
	public void setSCHOOLTAXDISTRICT3INDICATOR(String sCHOOLTAXDISTRICT3INDICATOR) {
		SCHOOLTAXDISTRICT3INDICATOR = sCHOOLTAXDISTRICT3INDICATOR;
	}
	public String getSITEINFLUENCE() {
		return SITEINFLUENCE;
	}
	public void setSITEINFLUENCE(String sITEINFLUENCE) {
		SITEINFLUENCE = sITEINFLUENCE;
	}
	public String getAMENITIES() {
		return AMENITIES;
	}
	public void setAMENITIES(String aMENITIES) {
		AMENITIES = aMENITIES;
	}
	public String getOTHERIMPRBUILDINGINDICATOR1() {
		return OTHERIMPRBUILDINGINDICATOR1;
	}
	public void setOTHERIMPRBUILDINGINDICATOR1(String oTHERIMPRBUILDINGINDICATOR1) {
		OTHERIMPRBUILDINGINDICATOR1 = oTHERIMPRBUILDINGINDICATOR1;
	}
	public String getOTHERIMPRBUILDINGINDICATOR2() {
		return OTHERIMPRBUILDINGINDICATOR2;
	}
	public void setOTHERIMPRBUILDINGINDICATOR2(String oTHERIMPRBUILDINGINDICATOR2) {
		OTHERIMPRBUILDINGINDICATOR2 = oTHERIMPRBUILDINGINDICATOR2;
	}
	public String getOTHERIMPRBUILDINGINDICATOR3() {
		return OTHERIMPRBUILDINGINDICATOR3;
	}
	public void setOTHERIMPRBUILDINGINDICATOR3(String oTHERIMPRBUILDINGINDICATOR3) {
		OTHERIMPRBUILDINGINDICATOR3 = oTHERIMPRBUILDINGINDICATOR3;
	}
	public String getOTHERIMPRBUILDINGINDICATOR4() {
		return OTHERIMPRBUILDINGINDICATOR4;
	}
	public void setOTHERIMPRBUILDINGINDICATOR4(String oTHERIMPRBUILDINGINDICATOR4) {
		OTHERIMPRBUILDINGINDICATOR4 = oTHERIMPRBUILDINGINDICATOR4;
	}
	public String getNEIGHBORHOODCODE() {
		return NEIGHBORHOODCODE;
	}
	public void setNEIGHBORHOODCODE(String nEIGHBORHOODCODE) {
		NEIGHBORHOODCODE = nEIGHBORHOODCODE;
	}
	public String getCONDOPROJECTBUILDINGNAME() {
		return CONDOPROJECTBUILDINGNAME;
	}
	public void setCONDOPROJECTBUILDINGNAME(String cONDOPROJECTBUILDINGNAME) {
		CONDOPROJECTBUILDINGNAME = cONDOPROJECTBUILDINGNAME;
	}
	public String getOTHERIMPRBUILDINGINDICATOR5() {
		return OTHERIMPRBUILDINGINDICATOR5;
	}
	public void setOTHERIMPRBUILDINGINDICATOR5(String oTHERIMPRBUILDINGINDICATOR5) {
		OTHERIMPRBUILDINGINDICATOR5 = oTHERIMPRBUILDINGINDICATOR5;
	}
	public String getAMENITIES2() {
		return AMENITIES2;
	}
	public void setAMENITIES2(String aMENITIES2) {
		AMENITIES2 = aMENITIES2;
	}
	public String getOTHERIMPRBUILDINGAREA1() {
		return OTHERIMPRBUILDINGAREA1;
	}
	public void setOTHERIMPRBUILDINGAREA1(String oTHERIMPRBUILDINGAREA1) {
		OTHERIMPRBUILDINGAREA1 = oTHERIMPRBUILDINGAREA1;
	}
	public String getOTHERIMPRBUILDINGAREA2() {
		return OTHERIMPRBUILDINGAREA2;
	}
	public void setOTHERIMPRBUILDINGAREA2(String oTHERIMPRBUILDINGAREA2) {
		OTHERIMPRBUILDINGAREA2 = oTHERIMPRBUILDINGAREA2;
	}
	public String getOTHERIMPRBUILDINGAREA3() {
		return OTHERIMPRBUILDINGAREA3;
	}
	public void setOTHERIMPRBUILDINGAREA3(String oTHERIMPRBUILDINGAREA3) {
		OTHERIMPRBUILDINGAREA3 = oTHERIMPRBUILDINGAREA3;
	}
	public String getOTHERIMPRBUILDINGAREA4() {
		return OTHERIMPRBUILDINGAREA4;
	}
	public void setOTHERIMPRBUILDINGAREA4(String oTHERIMPRBUILDINGAREA4) {
		OTHERIMPRBUILDINGAREA4 = oTHERIMPRBUILDINGAREA4;
	}
	public String getOTHERIMPRBUILDINGAREA5() {
		return OTHERIMPRBUILDINGAREA5;
	}
	public void setOTHERIMPRBUILDINGAREA5(String oTHERIMPRBUILDINGAREA5) {
		OTHERIMPRBUILDINGAREA5 = oTHERIMPRBUILDINGAREA5;
	}
	public String getOTHERROOMS() {
		return OTHERROOMS;
	}
	public void setOTHERROOMS(String oTHERROOMS) {
		OTHERROOMS = oTHERROOMS;
	}
	public String getEXTRAFEATURES1AREA() {
		return EXTRAFEATURES1AREA;
	}
	public void setEXTRAFEATURES1AREA(String eXTRAFEATURES1AREA) {
		EXTRAFEATURES1AREA = eXTRAFEATURES1AREA;
	}
	public String getEXTRAFEATURES1INDICATOR() {
		return EXTRAFEATURES1INDICATOR;
	}
	public void setEXTRAFEATURES1INDICATOR(String eXTRAFEATURES1INDICATOR) {
		EXTRAFEATURES1INDICATOR = eXTRAFEATURES1INDICATOR;
	}
	public String getTOPOGRAPHY() {
		return TOPOGRAPHY;
	}
	public void setTOPOGRAPHY(String tOPOGRAPHY) {
		TOPOGRAPHY = tOPOGRAPHY;
	}
	public String getROOFTYPE() {
		return ROOFTYPE;
	}
	public void setROOFTYPE(String rOOFTYPE) {
		ROOFTYPE = rOOFTYPE;
	}
	public String getEXTRAFEATURES2AREA() {
		return EXTRAFEATURES2AREA;
	}
	public void setEXTRAFEATURES2AREA(String eXTRAFEATURES2AREA) {
		EXTRAFEATURES2AREA = eXTRAFEATURES2AREA;
	}
	public String getEXTRAFEATURES2INDICATOR() {
		return EXTRAFEATURES2INDICATOR;
	}
	public void setEXTRAFEATURES2INDICATOR(String eXTRAFEATURES2INDICATOR) {
		EXTRAFEATURES2INDICATOR = eXTRAFEATURES2INDICATOR;
	}
	public String getEXTRAFEATURES3AREA() {
		return EXTRAFEATURES3AREA;
	}
	public void setEXTRAFEATURES3AREA(String eXTRAFEATURES3AREA) {
		EXTRAFEATURES3AREA = eXTRAFEATURES3AREA;
	}
	public String getEXTRAFEATURES3INDICATOR() {
		return EXTRAFEATURES3INDICATOR;
	}
	public void setEXTRAFEATURES3INDICATOR(String eXTRAFEATURES3INDICATOR) {
		EXTRAFEATURES3INDICATOR = eXTRAFEATURES3INDICATOR;
	}
	public String getEXTRAFEATURES4AREA() {
		return EXTRAFEATURES4AREA;
	}
	public void setEXTRAFEATURES4AREA(String eXTRAFEATURES4AREA) {
		EXTRAFEATURES4AREA = eXTRAFEATURES4AREA;
	}
	public String getEXTRAFEATURES4INDICATOR() {
		return EXTRAFEATURES4INDICATOR;
	}
	public void setEXTRAFEATURES4INDICATOR(String eXTRAFEATURES4INDICATOR) {
		EXTRAFEATURES4INDICATOR = eXTRAFEATURES4INDICATOR;
	}
	public String getOLDAPN() {
		return OLDAPN;
	}
	public void setOLDAPN(String oLDAPN) {
		OLDAPN = oLDAPN;
	}
	public String getBUILDINGCONDITION() {
		return BUILDINGCONDITION;
	}
	public void setBUILDINGCONDITION(String bUILDINGCONDITION) {
		BUILDINGCONDITION = bUILDINGCONDITION;
	}
	public String getLOTSIZEFRONTAGEFEET() {
		return LOTSIZEFRONTAGEFEET;
	}
	public void setLOTSIZEFRONTAGEFEET(String lOTSIZEFRONTAGEFEET) {
		LOTSIZEFRONTAGEFEET = lOTSIZEFRONTAGEFEET;
	}
	public String getLOTSIZEDEPTHFEET() {
		return LOTSIZEDEPTHFEET;
	}
	public void setLOTSIZEDEPTHFEET(String lOTSIZEDEPTHFEET) {
		LOTSIZEDEPTHFEET = lOTSIZEDEPTHFEET;
	}
	public String getCOMMENTS() {
		return COMMENTS;
	}
	public void setCOMMENTS(String cOMMENTS) {
		COMMENTS = cOMMENTS;
	}
	public String getWATER() {
		return WATER;
	}
	public void setWATER(String wATER) {
		WATER = wATER;
	}
	public String getSEWER() {
		return SEWER;
	}
	public void setSEWER(String sEWER) {
		SEWER = sEWER;
	}
	public String getNEWRECORDTYPE() {
		return NEWRECORDTYPE;
	}
	public void setNEWRECORDTYPE(String nEWRECORDTYPE) {
		NEWRECORDTYPE = nEWRECORDTYPE;
	}
	public TextFileDto(String sTATEPOSTALCODE, String cOUNTYNAME, String aPNORPINNUMBER,
			String dUPLICATEAPNMULTIADDRESSID, String pROPADDRSRCEFLAG, String pROPHOUSENUMBER, String pROPHOUSEALPHA,
			String pROPSTREETDIRECTIONLEFT, String pROPSTREETNAME, String pROPSTREETSUFFIX,
			String pROPSTREETDIRECTIONRIGHT, String pROPUNITNUMBER, String pROPFULLSTREETADDRESS, String pROPCITYNAME,
			String pROPSTATE, String pROPZIPCODE, String pROPZIP4, String aSSESSEEOWNERNAME,
			String sECOND_ASSESSEEOWNERNAME, String aSSEVESTINGIDCODE, String tAXACCOUNTNUMBER,
			String aSSEMAILCAREOFNAME, String aSSEMAILHOUSENUMBER, String aSSEMAILHOUSEALPHA,
			String aSSEMAILSTREETDIRECTIONLEFT, String aSSEMAILSTREETNAME, String aSSEMAILSTREETSUFFIX,
			String aSSEMAILSTREETDIRECTIONRIGHT, String aSSEMAILUNITNUMBER, String aSSEMAILFULLSTREETADDRESS,
			String aSSEMAILCITYNAME, String aSSEMAILSTATE, String aSSEMAILZIPCODE, String aSSEMAILZIP4,
			String sTATELANDUSECODE, String oWNEROCCUPIEDSFRCONDO, String aSSESSEDLANDVALUE,
			String aSSESSEDIMPROVEMENTVALUE, String tOTALASSESSEDVALUE, String aSSESSMENTYEAR,
			String cALIFHOMEOWNERSEXEMPTION, String tAXEXEMPTIONCODE, String tAXRATECODEAREA, String tAXAMOUNT,
			String tAXYEAR, String tAXDELINQUENTYEAR, String rECORDERSDOCUMENTNUMBER, String rECORDERSBOOKNUMBER,
			String rECORDERSPAGENUMBER, String rECORDINGDATE, String dOCUMENTTYPECOUNTYDESCRIPTION, String sALESPRICE,
			String sALESPRICECODE, String pRIORSALEDATE, String pRIORSALESPRICE, String pRIORSALESCODE,
			String lEGALLOTCODE, String lEGALLOTNUMBER, String lEGALLANDLOT, String lEGALBLOCK, String lEGALSECTION,
			String lEGALDISTRICT, String lEGALUNIT, String lEGALCITYMUNICIPALITYTOWNSHIP, String lEGALSUBDIVISIONNAME,
			String lEGALPHASENO, String lEGALTRACTNO, String lEGALSECTWPRNGMER, String lEGALBRIEFDESCRIPTION,
			String lEGALASSESSORSMAPREF, String cOUNTYLANDUSEDESCRIPTION, String cOUNTYLANDUSECODE,
			String sTANDARDIZEDLANDUSECODE, String tIMESHARECODE, String zONING, String lOTSIZEORAREA,
			String bUILDINGAREA, String yEARBUILT, String nOOFBUILDINGS, String nOOFSTORIES, String nOOFUNITS,
			String tOTALNOOFROOMS, String nOOFBEDROOMS, String nOOFBATHS, String nOOFPARTIALBATHS,
			String gARAGETYPEPARKING, String pARKINGNUMBEROFCARS, String pOOL, String mAILCITYSTZIP, String fIPSCODE,
			String tAPECUTDATE, String cENSUSTRACT, String rECORDTYPE, String mARKETVALUELAND,
			String mARKETVALUEIMPROVEMENT, String tOTALMARKETVALUE, String mARKETVALUEYEAR, String bUILDINGCLASS,
			String sTYLE, String tYPECONSTRUCTION, String eXTERIORWALLS, String fOUNDATION, String rOOFCOVER,
			String hEATING, String aIRCONDITIONING, String eLEVATOR, String fIREPLACE, String bASEMENT,
			String eDITIONNUMBER, String pROPERTYCOUNTRYCODE, String bUILDINGAREAINDICATOR, String pROPADDRMATCHCODE,
			String pROPADDRUNITDESIGNATOR, String pROPADDRUNITNUMBER, String pROPADDRCARRIERROUTE,
			String pROPADDRGEOCODEMATCHCODE, String pROPADDRLATITUDE, String pROPADDRLONGITUDE,
			String pROPADDRCENSUSTRACTBLOCK, String mAILADDRMATCHCODE, String mAILADDRUNITDESIGNATOR,
			String mAILADDRUNITNUMBER, String mAILADDRCARRIERROUTE, String aSSESSEEOWNERNAMEINDICATOR,
			String sECOND_ASSESSEEOWNER_INDICATOR, String mAILCAREOFNAMEINDICATOR, String aSSESSEEOWNERNAMETYPE,
			String sECONDASSESSEEOWNERNAMETYPE, String aLTOLDAPNINDICATOR, String cERTIFICATIONDATE, String lOTSIZESQFT,
			String bUILDINGQUALITY, String fLOORCOVER, String nOOFPLUMBINGFIXTURES, String bUILDINGAREA1,
			String bUILDINGAREA1INDICATOR, String bUILDINGAREA2, String bUILDINGAREA2INDICATOR, String bUILDINGAREA3,
			String bUILDINGAREA3INDICATOR, String bUILDINGAREA4, String bUILDINGAREA4INDICATOR, String bUILDINGAREA5,
			String bUILDINGAREA5INDICATOR, String bUILDINGAREA6, String bUILDINGAREA6INDICATOR, String bUILDINGAREA7,
			String bUILDINGAREA7INDICATOR, String eFFECTIVEYEARBUILT, String hEATINGFUELTYPE,
			String aIRCONDITIONINGTYPE, String lOTSIZEACRES, String mORTGAGELENDERNAME, String iNTERIORWALLS,
			String sCHOOLTAXDISTRICT1, String sCHOOLTAXDISTRICT1INDICATOR, String sCHOOLTAXDISTRICT2,
			String sCHOOLTAXDISTRICT2INDICATOR, String sCHOOLTAXDISTRICT3, String sCHOOLTAXDISTRICT3INDICATOR,
			String sITEINFLUENCE, String aMENITIES, String oTHERIMPRBUILDINGINDICATOR1,
			String oTHERIMPRBUILDINGINDICATOR2, String oTHERIMPRBUILDINGINDICATOR3, String oTHERIMPRBUILDINGINDICATOR4,
			String nEIGHBORHOODCODE, String cONDOPROJECTBUILDINGNAME, String oTHERIMPRBUILDINGINDICATOR5,
			String aMENITIES2, String oTHERIMPRBUILDINGAREA1, String oTHERIMPRBUILDINGAREA2,
			String oTHERIMPRBUILDINGAREA3, String oTHERIMPRBUILDINGAREA4, String oTHERIMPRBUILDINGAREA5,
			String oTHERROOMS, String eXTRAFEATURES1AREA, String eXTRAFEATURES1INDICATOR, String tOPOGRAPHY,
			String rOOFTYPE, String eXTRAFEATURES2AREA, String eXTRAFEATURES2INDICATOR, String eXTRAFEATURES3AREA,
			String eXTRAFEATURES3INDICATOR, String eXTRAFEATURES4AREA, String eXTRAFEATURES4INDICATOR, String oLDAPN,
			String bUILDINGCONDITION, String lOTSIZEFRONTAGEFEET, String lOTSIZEDEPTHFEET, String cOMMENTS,
			String wATER, String sEWER, String nEWRECORDTYPE) {
		super();
		STATEPOSTALCODE = sTATEPOSTALCODE;
		COUNTYNAME = cOUNTYNAME;
		APNORPINNUMBER = aPNORPINNUMBER;
		DUPLICATEAPNMULTIADDRESSID = dUPLICATEAPNMULTIADDRESSID;
		PROPADDRSRCEFLAG = pROPADDRSRCEFLAG;
		PROPHOUSENUMBER = pROPHOUSENUMBER;
		PROPHOUSEALPHA = pROPHOUSEALPHA;
		PROPSTREETDIRECTIONLEFT = pROPSTREETDIRECTIONLEFT;
		PROPSTREETNAME = pROPSTREETNAME;
		PROPSTREETSUFFIX = pROPSTREETSUFFIX;
		PROPSTREETDIRECTIONRIGHT = pROPSTREETDIRECTIONRIGHT;
		PROPUNITNUMBER = pROPUNITNUMBER;
		PROPFULLSTREETADDRESS = pROPFULLSTREETADDRESS;
		PROPCITYNAME = pROPCITYNAME;
		PROPSTATE = pROPSTATE;
		PROPZIPCODE = pROPZIPCODE;
		PROPZIP4 = pROPZIP4;
		ASSESSEEOWNERNAME = aSSESSEEOWNERNAME;
		SECOND_ASSESSEEOWNERNAME = sECOND_ASSESSEEOWNERNAME;
		ASSEVESTINGIDCODE = aSSEVESTINGIDCODE;
		TAXACCOUNTNUMBER = tAXACCOUNTNUMBER;
		ASSEMAILCAREOFNAME = aSSEMAILCAREOFNAME;
		ASSEMAILHOUSENUMBER = aSSEMAILHOUSENUMBER;
		ASSEMAILHOUSEALPHA = aSSEMAILHOUSEALPHA;
		ASSEMAILSTREETDIRECTIONLEFT = aSSEMAILSTREETDIRECTIONLEFT;
		ASSEMAILSTREETNAME = aSSEMAILSTREETNAME;
		ASSEMAILSTREETSUFFIX = aSSEMAILSTREETSUFFIX;
		ASSEMAILSTREETDIRECTIONRIGHT = aSSEMAILSTREETDIRECTIONRIGHT;
		ASSEMAILUNITNUMBER = aSSEMAILUNITNUMBER;
		ASSEMAILFULLSTREETADDRESS = aSSEMAILFULLSTREETADDRESS;
		ASSEMAILCITYNAME = aSSEMAILCITYNAME;
		ASSEMAILSTATE = aSSEMAILSTATE;
		ASSEMAILZIPCODE = aSSEMAILZIPCODE;
		ASSEMAILZIP4 = aSSEMAILZIP4;
		STATELANDUSECODE = sTATELANDUSECODE;
		OWNEROCCUPIEDSFRCONDO = oWNEROCCUPIEDSFRCONDO;
		ASSESSEDLANDVALUE = aSSESSEDLANDVALUE;
		ASSESSEDIMPROVEMENTVALUE = aSSESSEDIMPROVEMENTVALUE;
		TOTALASSESSEDVALUE = tOTALASSESSEDVALUE;
		ASSESSMENTYEAR = aSSESSMENTYEAR;
		CALIFHOMEOWNERSEXEMPTION = cALIFHOMEOWNERSEXEMPTION;
		TAXEXEMPTIONCODE = tAXEXEMPTIONCODE;
		TAXRATECODEAREA = tAXRATECODEAREA;
		TAXAMOUNT = tAXAMOUNT;
		TAXYEAR = tAXYEAR;
		TAXDELINQUENTYEAR = tAXDELINQUENTYEAR;
		RECORDERSDOCUMENTNUMBER = rECORDERSDOCUMENTNUMBER;
		RECORDERSBOOKNUMBER = rECORDERSBOOKNUMBER;
		RECORDERSPAGENUMBER = rECORDERSPAGENUMBER;
		RECORDINGDATE = rECORDINGDATE;
		DOCUMENTTYPECOUNTYDESCRIPTION = dOCUMENTTYPECOUNTYDESCRIPTION;
		SALESPRICE = sALESPRICE;
		SALESPRICECODE = sALESPRICECODE;
		PRIORSALEDATE = pRIORSALEDATE;
		PRIORSALESPRICE = pRIORSALESPRICE;
		PRIORSALESCODE = pRIORSALESCODE;
		LEGALLOTCODE = lEGALLOTCODE;
		LEGALLOTNUMBER = lEGALLOTNUMBER;
		LEGALLANDLOT = lEGALLANDLOT;
		LEGALBLOCK = lEGALBLOCK;
		LEGALSECTION = lEGALSECTION;
		LEGALDISTRICT = lEGALDISTRICT;
		LEGALUNIT = lEGALUNIT;
		LEGALCITYMUNICIPALITYTOWNSHIP = lEGALCITYMUNICIPALITYTOWNSHIP;
		LEGALSUBDIVISIONNAME = lEGALSUBDIVISIONNAME;
		LEGALPHASENO = lEGALPHASENO;
		LEGALTRACTNO = lEGALTRACTNO;
		LEGALSECTWPRNGMER = lEGALSECTWPRNGMER;
		LEGALBRIEFDESCRIPTION = lEGALBRIEFDESCRIPTION;
		LEGALASSESSORSMAPREF = lEGALASSESSORSMAPREF;
		COUNTYLANDUSEDESCRIPTION = cOUNTYLANDUSEDESCRIPTION;
		COUNTYLANDUSECODE = cOUNTYLANDUSECODE;
		STANDARDIZEDLANDUSECODE = sTANDARDIZEDLANDUSECODE;
		TIMESHARECODE = tIMESHARECODE;
		ZONING = zONING;
		LOTSIZEORAREA = lOTSIZEORAREA;
		BUILDINGAREA = bUILDINGAREA;
		YEARBUILT = yEARBUILT;
		NOOFBUILDINGS = nOOFBUILDINGS;
		NOOFSTORIES = nOOFSTORIES;
		NOOFUNITS = nOOFUNITS;
		TOTALNOOFROOMS = tOTALNOOFROOMS;
		NOOFBEDROOMS = nOOFBEDROOMS;
		NOOFBATHS = nOOFBATHS;
		NOOFPARTIALBATHS = nOOFPARTIALBATHS;
		GARAGETYPEPARKING = gARAGETYPEPARKING;
		PARKINGNUMBEROFCARS = pARKINGNUMBEROFCARS;
		POOL = pOOL;
		MAILCITYSTZIP = mAILCITYSTZIP;
		FIPSCODE = fIPSCODE;
		TAPECUTDATE = tAPECUTDATE;
		CENSUSTRACT = cENSUSTRACT;
		RECORDTYPE = rECORDTYPE;
		MARKETVALUELAND = mARKETVALUELAND;
		MARKETVALUEIMPROVEMENT = mARKETVALUEIMPROVEMENT;
		TOTALMARKETVALUE = tOTALMARKETVALUE;
		MARKETVALUEYEAR = mARKETVALUEYEAR;
		BUILDINGCLASS = bUILDINGCLASS;
		STYLE = sTYLE;
		TYPECONSTRUCTION = tYPECONSTRUCTION;
		EXTERIORWALLS = eXTERIORWALLS;
		FOUNDATION = fOUNDATION;
		ROOFCOVER = rOOFCOVER;
		HEATING = hEATING;
		AIRCONDITIONING = aIRCONDITIONING;
		ELEVATOR = eLEVATOR;
		FIREPLACE = fIREPLACE;
		BASEMENT = bASEMENT;
		EDITIONNUMBER = eDITIONNUMBER;
		PROPERTYCOUNTRYCODE = pROPERTYCOUNTRYCODE;
		BUILDINGAREAINDICATOR = bUILDINGAREAINDICATOR;
		PROPADDRMATCHCODE = pROPADDRMATCHCODE;
		PROPADDRUNITDESIGNATOR = pROPADDRUNITDESIGNATOR;
		PROPADDRUNITNUMBER = pROPADDRUNITNUMBER;
		PROPADDRCARRIERROUTE = pROPADDRCARRIERROUTE;
		PROPADDRGEOCODEMATCHCODE = pROPADDRGEOCODEMATCHCODE;
		PROPADDRLATITUDE = pROPADDRLATITUDE;
		PROPADDRLONGITUDE = pROPADDRLONGITUDE;
		PROPADDRCENSUSTRACTBLOCK = pROPADDRCENSUSTRACTBLOCK;
		MAILADDRMATCHCODE = mAILADDRMATCHCODE;
		MAILADDRUNITDESIGNATOR = mAILADDRUNITDESIGNATOR;
		MAILADDRUNITNUMBER = mAILADDRUNITNUMBER;
		MAILADDRCARRIERROUTE = mAILADDRCARRIERROUTE;
		ASSESSEEOWNERNAMEINDICATOR = aSSESSEEOWNERNAMEINDICATOR;
		SECOND_ASSESSEEOWNER_INDICATOR = sECOND_ASSESSEEOWNER_INDICATOR;
		MAILCAREOFNAMEINDICATOR = mAILCAREOFNAMEINDICATOR;
		ASSESSEEOWNERNAMETYPE = aSSESSEEOWNERNAMETYPE;
		SECONDASSESSEEOWNERNAMETYPE = sECONDASSESSEEOWNERNAMETYPE;
		ALTOLDAPNINDICATOR = aLTOLDAPNINDICATOR;
		CERTIFICATIONDATE = cERTIFICATIONDATE;
		LOTSIZESQFT = lOTSIZESQFT;
		BUILDINGQUALITY = bUILDINGQUALITY;
		FLOORCOVER = fLOORCOVER;
		NOOFPLUMBINGFIXTURES = nOOFPLUMBINGFIXTURES;
		BUILDINGAREA1 = bUILDINGAREA1;
		BUILDINGAREA1INDICATOR = bUILDINGAREA1INDICATOR;
		BUILDINGAREA2 = bUILDINGAREA2;
		BUILDINGAREA2INDICATOR = bUILDINGAREA2INDICATOR;
		BUILDINGAREA3 = bUILDINGAREA3;
		BUILDINGAREA3INDICATOR = bUILDINGAREA3INDICATOR;
		BUILDINGAREA4 = bUILDINGAREA4;
		BUILDINGAREA4INDICATOR = bUILDINGAREA4INDICATOR;
		BUILDINGAREA5 = bUILDINGAREA5;
		BUILDINGAREA5INDICATOR = bUILDINGAREA5INDICATOR;
		BUILDINGAREA6 = bUILDINGAREA6;
		BUILDINGAREA6INDICATOR = bUILDINGAREA6INDICATOR;
		BUILDINGAREA7 = bUILDINGAREA7;
		BUILDINGAREA7INDICATOR = bUILDINGAREA7INDICATOR;
		EFFECTIVEYEARBUILT = eFFECTIVEYEARBUILT;
		HEATINGFUELTYPE = hEATINGFUELTYPE;
		AIRCONDITIONINGTYPE = aIRCONDITIONINGTYPE;
		LOTSIZEACRES = lOTSIZEACRES;
		MORTGAGELENDERNAME = mORTGAGELENDERNAME;
		INTERIORWALLS = iNTERIORWALLS;
		SCHOOLTAXDISTRICT1 = sCHOOLTAXDISTRICT1;
		SCHOOLTAXDISTRICT1INDICATOR = sCHOOLTAXDISTRICT1INDICATOR;
		SCHOOLTAXDISTRICT2 = sCHOOLTAXDISTRICT2;
		SCHOOLTAXDISTRICT2INDICATOR = sCHOOLTAXDISTRICT2INDICATOR;
		SCHOOLTAXDISTRICT3 = sCHOOLTAXDISTRICT3;
		SCHOOLTAXDISTRICT3INDICATOR = sCHOOLTAXDISTRICT3INDICATOR;
		SITEINFLUENCE = sITEINFLUENCE;
		AMENITIES = aMENITIES;
		OTHERIMPRBUILDINGINDICATOR1 = oTHERIMPRBUILDINGINDICATOR1;
		OTHERIMPRBUILDINGINDICATOR2 = oTHERIMPRBUILDINGINDICATOR2;
		OTHERIMPRBUILDINGINDICATOR3 = oTHERIMPRBUILDINGINDICATOR3;
		OTHERIMPRBUILDINGINDICATOR4 = oTHERIMPRBUILDINGINDICATOR4;
		NEIGHBORHOODCODE = nEIGHBORHOODCODE;
		CONDOPROJECTBUILDINGNAME = cONDOPROJECTBUILDINGNAME;
		OTHERIMPRBUILDINGINDICATOR5 = oTHERIMPRBUILDINGINDICATOR5;
		AMENITIES2 = aMENITIES2;
		OTHERIMPRBUILDINGAREA1 = oTHERIMPRBUILDINGAREA1;
		OTHERIMPRBUILDINGAREA2 = oTHERIMPRBUILDINGAREA2;
		OTHERIMPRBUILDINGAREA3 = oTHERIMPRBUILDINGAREA3;
		OTHERIMPRBUILDINGAREA4 = oTHERIMPRBUILDINGAREA4;
		OTHERIMPRBUILDINGAREA5 = oTHERIMPRBUILDINGAREA5;
		OTHERROOMS = oTHERROOMS;
		EXTRAFEATURES1AREA = eXTRAFEATURES1AREA;
		EXTRAFEATURES1INDICATOR = eXTRAFEATURES1INDICATOR;
		TOPOGRAPHY = tOPOGRAPHY;
		ROOFTYPE = rOOFTYPE;
		EXTRAFEATURES2AREA = eXTRAFEATURES2AREA;
		EXTRAFEATURES2INDICATOR = eXTRAFEATURES2INDICATOR;
		EXTRAFEATURES3AREA = eXTRAFEATURES3AREA;
		EXTRAFEATURES3INDICATOR = eXTRAFEATURES3INDICATOR;
		EXTRAFEATURES4AREA = eXTRAFEATURES4AREA;
		EXTRAFEATURES4INDICATOR = eXTRAFEATURES4INDICATOR;
		OLDAPN = oLDAPN;
		BUILDINGCONDITION = bUILDINGCONDITION;
		LOTSIZEFRONTAGEFEET = lOTSIZEFRONTAGEFEET;
		LOTSIZEDEPTHFEET = lOTSIZEDEPTHFEET;
		COMMENTS = cOMMENTS;
		WATER = wATER;
		SEWER = sEWER;
		NEWRECORDTYPE = nEWRECORDTYPE;
	}*/
	public TextFileDto() {
		super();
		// TODO Auto-generated constructor stub
	}
	public TextFileDto(String sTATEPOSTALCODE, String cOUNTYNAME, String aPNORPINNUMBER,
			String dUPLICATEAPNMULTIADDRESSID, String pROPADDRSRCEFLAG, String pROPHOUSENUMBER, String pROPHOUSEALPHA,
			String pROPSTREETDIRECTIONLEFT, String pROPSTREETNAME, String pROPSTREETSUFFIX,
			String pROPSTREETDIRECTIONRIGHT, String pROPUNITNUMBER, String pROPFULLSTREETADDRESS, String pROPCITYNAME,
			String pROPSTATE, String pROPZIPCODE, String pROPZIP4, String aSSESSEEOWNERNAME,
			String sECOND_ASSESSEEOWNERNAME, String aSSEVESTINGIDCODE, String tAXACCOUNTNUMBER,
			String aSSEMAILCAREOFNAME, String aSSEMAILHOUSENUMBER, String aSSEMAILHOUSEALPHA,
			String aSSEMAILSTREETDIRECTIONLEFT, String aSSEMAILSTREETNAME, String aSSEMAILSTREETSUFFIX,
			String aSSEMAILSTREETDIRECTIONRIGHT, String aSSEMAILUNITNUMBER, String aSSEMAILFULLSTREETADDRESS,
			String aSSEMAILCITYNAME, String aSSEMAILSTATE, String aSSEMAILZIPCODE, String aSSEMAILZIP4,
			String sTATELANDUSECODE, String oWNEROCCUPIEDSFRCONDO, String aSSESSEDLANDVALUE,
			String aSSESSEDIMPROVEMENTVALUE, String tOTALASSESSEDVALUE, String aSSESSMENTYEAR,
			String cALIFHOMEOWNERSEXEMPTION, String tAXEXEMPTIONCODE, String tAXRATECODEAREA, String tAXAMOUNT,
			String tAXYEAR, String tAXDELINQUENTYEAR, String rECORDERSDOCUMENTNUMBER, String rECORDERSBOOKNUMBER,
			String rECORDERSPAGENUMBER, String rECORDINGDATE, String dOCUMENTTYPECOUNTYDESCRIPTION, String sALESPRICE,
			String sALESPRICECODE, String pRIORSALEDATE, String pRIORSALESPRICE) {
		super();
		STATEPOSTALCODE = sTATEPOSTALCODE;
		COUNTYNAME = cOUNTYNAME;
		APNORPINNUMBER = aPNORPINNUMBER;
		DUPLICATEAPNMULTIADDRESSID = dUPLICATEAPNMULTIADDRESSID;
		PROPADDRSRCEFLAG = pROPADDRSRCEFLAG;
		PROPHOUSENUMBER = pROPHOUSENUMBER;
		PROPHOUSEALPHA = pROPHOUSEALPHA;
		PROPSTREETDIRECTIONLEFT = pROPSTREETDIRECTIONLEFT;
		PROPSTREETNAME = pROPSTREETNAME;
		PROPSTREETSUFFIX = pROPSTREETSUFFIX;
		PROPSTREETDIRECTIONRIGHT = pROPSTREETDIRECTIONRIGHT;
		PROPUNITNUMBER = pROPUNITNUMBER;
		PROPFULLSTREETADDRESS = pROPFULLSTREETADDRESS;
		PROPCITYNAME = pROPCITYNAME;
		PROPSTATE = pROPSTATE;
		PROPZIPCODE = pROPZIPCODE;
		PROPZIP4 = pROPZIP4;
		ASSESSEEOWNERNAME = aSSESSEEOWNERNAME;
		SECOND_ASSESSEEOWNERNAME = sECOND_ASSESSEEOWNERNAME;
		ASSEVESTINGIDCODE = aSSEVESTINGIDCODE;
		TAXACCOUNTNUMBER = tAXACCOUNTNUMBER;
		ASSEMAILCAREOFNAME = aSSEMAILCAREOFNAME;
		ASSEMAILHOUSENUMBER = aSSEMAILHOUSENUMBER;
		ASSEMAILHOUSEALPHA = aSSEMAILHOUSEALPHA;
		ASSEMAILSTREETDIRECTIONLEFT = aSSEMAILSTREETDIRECTIONLEFT;
		ASSEMAILSTREETNAME = aSSEMAILSTREETNAME;
		ASSEMAILSTREETSUFFIX = aSSEMAILSTREETSUFFIX;
		ASSEMAILSTREETDIRECTIONRIGHT = aSSEMAILSTREETDIRECTIONRIGHT;
		ASSEMAILUNITNUMBER = aSSEMAILUNITNUMBER;
		ASSEMAILFULLSTREETADDRESS = aSSEMAILFULLSTREETADDRESS;
		ASSEMAILCITYNAME = aSSEMAILCITYNAME;
		ASSEMAILSTATE = aSSEMAILSTATE;
		ASSEMAILZIPCODE = aSSEMAILZIPCODE;
		ASSEMAILZIP4 = aSSEMAILZIP4;
		STATELANDUSECODE = sTATELANDUSECODE;
		OWNEROCCUPIEDSFRCONDO = oWNEROCCUPIEDSFRCONDO;
		ASSESSEDLANDVALUE = aSSESSEDLANDVALUE;
		ASSESSEDIMPROVEMENTVALUE = aSSESSEDIMPROVEMENTVALUE;
		TOTALASSESSEDVALUE = tOTALASSESSEDVALUE;
		ASSESSMENTYEAR = aSSESSMENTYEAR;
		CALIFHOMEOWNERSEXEMPTION = cALIFHOMEOWNERSEXEMPTION;
		TAXEXEMPTIONCODE = tAXEXEMPTIONCODE;
		TAXRATECODEAREA = tAXRATECODEAREA;
		TAXAMOUNT = tAXAMOUNT;
		TAXYEAR = tAXYEAR;
		TAXDELINQUENTYEAR = tAXDELINQUENTYEAR;
		RECORDERSDOCUMENTNUMBER = rECORDERSDOCUMENTNUMBER;
		RECORDERSBOOKNUMBER = rECORDERSBOOKNUMBER;
		RECORDERSPAGENUMBER = rECORDERSPAGENUMBER;
		RECORDINGDATE = rECORDINGDATE;
		DOCUMENTTYPECOUNTYDESCRIPTION = dOCUMENTTYPECOUNTYDESCRIPTION;
		SALESPRICE = sALESPRICE;
		SALESPRICECODE = sALESPRICECODE;
		PRIORSALEDATE = pRIORSALEDATE;
		PRIORSALESPRICE = pRIORSALESPRICE;
	}
	
	
}
